### ISSUE TITLE
Collect all projects and ref?

### ISSUE THREAD

**Issue by jeff-cook** [mvisonneau/gitlab-ci-pipelines-exporter#1]
This is a great project. 

I was wondering if there was a way to get all projects and ref? As the list of projects grows having everything monitored would be great. Instead of having to build a script to build the config file?

To handle limiting the scope we could make sure the token user only has access to the right projects. 

Thank you for your work on this.

**Comment by snahelou** [comment]
Hello

I started to integrate wildcard support. It's quick&dirty, but it works.
https://github.com/snahelou/gitlab-ci-pipelines-exporter

BR

**Comment by Sakojpa** [comment]
Hi!
nice. but it fetch only 20 projects with wildcard and all, other projects can be fetch by config.yml ?

**Comment by mvisonneau** [comment]
👋 that would be really cool to have indeed. Not sure if there is an easy/efficient way to list the projects that the token has access onto. It could get easily expensive to have to loop in order to determine it. If someone has a solution I'd be more than happy to get it merged.

**Comment by Sakojpa** [comment]
I got an error, I can not understand what it is

2019/02/12 06:48:56 -> Starting exporter
2019/02/12 06:48:56 -> Polling *** every 30s
2019/02/12 06:48:56 -> 10 project(s) configured
2019/02/12 06:48:56 --> Polling ID: 286 | ***
...
2019/02/12 06:48:56 --> Polling ID: 261 | ***
panic: runtime error: index out of range

goroutine 16 [running]:
main.main.func1(0xc42009b200, 0xc4200165c0, 0xc420012e60, 0x11, 0xc420014cc0, 0x6)
	/go/src/github.com/mvisonneau/gitlab-ci-pipelines-exporter/main.go:127 +0xafb
created by main.main
	/go/src/github.com/mvisonneau/gitlab-ci-pipelines-exporter/main.go:108 +0x316

**Comment by mvisonneau** [comment]
I just added this feature with https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/2713ebdfa53d676e350ba651cc744a31b5fbbe77 !
