### ISSUE TITLE
Freshly archived projects don't get removed from polling for pipelines

### ISSUE THREAD

**Issue by DJMatus23** [mvisonneau/gitlab-ci-pipelines-exporter#101]
If a project A was active when the exporter starts, then after polling starts, you archive it, the exporter doesn't check it again, and thus you end up with archived projects reporting old pipelines.

We found this, because when we rolled it out to all of our teams, it became a bit of a competition to see who could clean up their pipelines the best - which was great, but then we had to implement a nightly job to restart the exporter. :(

I think it would be better if, during polling for new projects, old/archived projects were also removed.

**Comment by mvisonneau** [comment]
Indeed, we do not have any kind of logic to handle this case yet.

**Comment by mvisonneau** [comment]
👋 hey @DJMatus23 , I just finished implementing this feature, it is part of the [0.4.1](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.1) release. For more info on how it works you can refer to this commit : 092bf6363e2ec031b22fc37f49faa2fd53c13726

I hope this will sort your issues out!

**Comment by DJMatus23** [comment]
That's awesome, thank you so much @mvisonneau - I had hoped to do more work on this exporter but I've not been able to make any time due to everything that's been going on this year.
