### ISSUE TITLE
Unable To Deploy Using Helm To My Kubernetes Cluster

### ISSUE THREAD

**Issue by adeadeabodunrin** [mvisonneau/gitlab-ci-pipelines-exporter#105]
First of all, let me say a very big thank you for this excellent work. 

Am trying to deploy this to a KUbernetes cluster using helm. I successfully edited the config section of values.yaml by adding my projects and token. Howeever, when I run the command "helm upgrade -i gitlab-ci-pipelines-exporter ./chart -f values.yml", I keep getting the error message "Error: path "./chart" not found". Is it that the helm chart is not fully ready? How can I deploy this to a Kubernetes Cluster? Please assist

**Comment by mvisonneau** [comment]
👋 hey @adeadeabodunrin, thank you for the very kind feedback 🙇 

Are you located into the correct folder? What does `ls -l ./chart` gives you?

**Comment by adeadeabodunrin** [comment]
Thanks for your response.

Yes I am in the right folder but stranger things have happened before....
total 16
-rw-r--r--@ 1 aa  staff   165 Apr  8 22:31 Chart.yaml
drwxr-xr-x  2 aa  staff    64 May 27 04:59 charts
drwxr-xr-x  6 aa  staff   192 Apr  8 22:31 templates
-rw-r--r--@ 1 aa staff  2909 May 26 20:40 values.yaml

**Comment by mvisonneau** [comment]
you should not have a `charts/` folder.
Looking at the timestamps and sizes it does not look like the latest version of repo, I would recommend to update your repo against the `master` branch

**Comment by adeadeabodunrin** [comment]
Thanks for your response....I updated the repo and was still having the same issue but I tried a different command: helm upgrade -i gitlab-ci-pipelines-exporter ./chart rather than "helm upgrade -i gitlab-ci-pipelines-exporter ./chart -f values.yml" as suggested and it worked.
