### ISSUE TITLE
Crash Loop Back After Installing on Minikube Using The Helm Chart

### ISSUE THREAD

**Issue by adeadeabodunrin** [mvisonneau/gitlab-ci-pipelines-exporter#109]
Thanks again for your help! After deploying to Minikube with the command to deploy using Helm Chart, the pod is not running. Stays in CrashLoopBackOff. Did you ever encounter this and what can I be doing wrong.

Kubectl describe pod gives the below:

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned default/gitlab-ci-pipelines-exporter-679669d4fd-svtzb to minikube
  Normal   Pulled     12m (x5 over 13m)     kubelet, minikube  Container image "mvisonneau/gitlab-ci-pipelines-exporter:0.3.2" already present on machine
  Normal   Created    12m (x5 over 13m)     kubelet, minikube  Created container gitlab-ci-pipelines-exporter
  Normal   Started    12m (x5 over 13m)     kubelet, minikube  Started container gitlab-ci-pipelines-exporter
  Warning  BackOff    3m41s (x53 over 13m)  kubelet, minikube  Back-off restarting failed container

**Comment by mvisonneau** [comment]
what do you have in the logs ? `kubectl logs -p <pod_name>`

**Comment by notariuss** [comment]
@adeadeabodunrin try to set `config.gitlab.health_url` to https://gitlab.com/

**Comment by adeadeabodunrin** [comment]
Thanks to 

> what do you have in the logs ? `kubectl logs -p <pod_name>`

Thanks to you. I ran the command and found "{"level":"error","msg":"you need to configure at least one project/wildcard to poll, none given","time":"2020-05-31T03:18:36Z"}"

So I figured that something was wrong with my config. I corrected the config file and it is now running.

Now I need to figure out how to expose the service so I can know it's polling

**Comment by adeadeabodunrin** [comment]
> @adeadeabodunrin try to set `config.gitlab.health_url` to https://gitlab.com/

Thanks @notariuss , my config was wrong.

**Comment by mvisonneau** [comment]
sound good, thanks for the feedback! I'll close this issue then!
