### ISSUE TITLE
Can we create custom dashboards here. 

### ISSUE THREAD

**Issue by syedsfayaz** [mvisonneau/gitlab-ci-pipelines-exporter#11]
Since We can monitor git lab repos here. Can we also monitor status of any other sources like jenkins. 
 
I have just added an example here on this link. 
https://community.grafana.com/t/custom-dashboard-to-show-builds-progress/19871

**Comment by mvisonneau** [comment]
Hey @syedsfayaz, thanks for your question/suggestion! However, it looks quite unrelated to the purpose of this tool which is architected around GitLab fashioned pipelines and projects. I believe that creating a dedicated project/exporter for Jenkins or else would be a better option.
