### ISSUE TITLE
error="could not find any pipeline for project

### ISSUE THREAD

**Issue by mkrvanton** [mvisonneau/gitlab-ci-pipelines-exporter#111]
Hi, I got multiple errors during "discovered new project", as a result, my metrics have old values.
Have you ever see something like that? How can I solve it?

gitlab-ci-pipelines-exporter/config.yml

gitlab:
  url: https://gitlab.XXyyXXyyXX.com
  token: XXyyXXyyXX
projects:
  - name: test/test-tmp
    refs_regexp: ".*"
    fetch_pipeline_job_metrics: true

docker logs example_gitlab-ci-pipelines-exporter_1
`
 time="2020-06-01T09:04:57Z" level=info msg="starting exporter" discover-projects-refs-interval=300s discover-wildcard-projects-interval=1800s gitlab-endpoint="https://gitlab.XX.YY" on-init-fetch-refs-from-pipelines=false polling-projects-refs-interval=30s polling-workers=2 rate-limit=10rps

 time="2020-06-01T09:04:57Z" level=info msg="started, now serving requests" listen-address=":8080"

 time="2020-06-01T09:04:57Z" level=info msg="discover wildcards" total=0
...

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-1 	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-2 	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-3	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-4	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-5	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-6	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="discovered new project ref" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-7	project-ref-kind=branch	

 time="2020-06-01T09:05:06Z" level=info msg="polling metrics from projects refs" total=220				

 time="2020-06-01T09:05:06Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-8" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-8	project-ref-kind=branch

 time="2020-06-01T09:05:06Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-9" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-9	project-ref-kind=branch

 time="2020-06-01T09:05:07Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-10" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-10	

 time="2020-06-01T09:05:07Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-11" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-11	project-ref-kind=branch

 time="2020-06-01T09:05:07Z" level=info msg="Found 1 jobs for pipeline 807624"				

 time="2020-06-01T09:05:07Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-12" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-12	project-ref-kind=branch

 time="2020-06-01T09:05:07Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-13" project-id=1427	 project-path-with-namespace=test/test-tmp project-ref=	release-13	project-ref-kind=branch

 time="2020-06-01T09:05:08Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-14" project-id=1428	 project-path-with-namespace=test/test-tmp project-ref=	release-14	project-ref-kind=branch

 time="2020-06-01T09:05:08Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-15" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-15	project-ref-kind=branch

 time="2020-06-01T09:05:08Z" level=info msg="Found 1 jobs for pipeline 706844"				

 time="2020-06-01T09:05:08Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-16" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-16	project-ref-kind=branch

 time="2020-06-01T09:05:09Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-17" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-17	project-ref-kind=branch

 time="2020-06-01T09:05:09Z" level=info msg="Found 20 jobs for pipeline 648428"				

 time="2020-06-01T09:05:09Z" level=info msg="Found 20 jobs for pipeline 648428"				

 time="2020-06-01T09:05:09Z" level=info msg="Found 20 jobs for pipeline 879507"				

 time="2020-06-01T09:05:09Z" level=info msg="Found 20 jobs for pipeline 648428"				

 time="2020-06-01T09:05:10Z" level=info msg="Found 13 jobs for pipeline 879507"				

 time="2020-06-01T09:05:10Z" level=info msg="Found 20 jobs for pipeline 648428"				

 time="2020-06-01T09:05:10Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-18" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-18	project-ref-kind=branch

 time="2020-06-01T09:05:10Z" level=info msg="Found 20 jobs for pipeline 648428"				

 time="2020-06-01T09:05:11Z" level=info msg="Found 1 jobs for pipeline 706884"				

 time="2020-06-01T09:05:11Z" level=info msg="Found 18 jobs for pipeline 756662"				

 time="2020-06-01T09:05:11Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-19" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-19	project-ref-kind=branch

 time="2020-06-01T09:05:11Z" level=info msg="Found 1 jobs for pipeline 74911"				

 time="2020-06-01T09:05:11Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-20" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-20	project-ref-kind=branch

 time="2020-06-01T09:05:12Z" level=info msg="Found 20 jobs for pipeline 695087"				

 time="2020-06-01T09:05:12Z" level=info msg="Found 14 jobs for pipeline 719160"				

 time="2020-06-01T09:05:12Z" level=info msg="Found 4 jobs for pipeline 695087"				

 time="2020-06-01T09:05:13Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-21" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-21	project-ref-kind=branch

 time="2020-06-01T09:05:13Z" level=error msg="whilst metrics from polling projects refs" error="could not find any pipeline for project test/test-tmp with ref 	release-22" project-id=1429	 project-path-with-namespace=test/test-tmp project-ref=	release-22	project-ref-kind=branch

 time="2020-06-01T09:05:13Z" level=info msg="Found 8 jobs for pipeline 881995"				
`

**Comment by mvisonneau** [comment]
👋 hey @mkrvanton, those errors can occur when project branches haven't got pipelines on them. They are safe the ignore, if you want to get rid of them you will need to update your `refs_regexp` to exlude them from being polled.

Regarding your metrics not being updated, which version are you using? I have fixed a bunch of related issues in the last release (0.3.2).

**Comment by mkrvanton** [comment]
Thank you so much for your response, now is pretty clear about "project branches".
Regarding metrics updates, I will create a separate issue, cause it is not related to that question.
