### ISSUE TITLE
Polystat panel top right corner not populated 

### ISSUE THREAD

**Issue by tanmoyrsc** [mvisonneau/gitlab-ci-pipelines-exporter#114]
Hi,

Today I have integrated gitlab-ci exporter. All data are coming properly, except Polystat panel, is it takes long time to populate or I did some mis-configuration?

Br,
Tanmoy

**Comment by iormundr** [comment]
I have the same issue

**Comment by mvisonneau** [comment]
Hi @tanmoyrsc, it should be automatically polling data. If you are seeing some in the table I reckon there might be something wrong with your Grafana setup.

I just tested it locally from the [example](example/), it seems to work fine.

**Comment by mvisonneau** [comment]
I am going to close it as this issue has gone stale + I am not planning to provide support over Grafana plugins :)
