### ISSUE TITLE
Pod Not in Ready State

### ISSUE THREAD

**Issue by adeadeabodunrin** [mvisonneau/gitlab-ci-pipelines-exporter#115]
I have tried everything but after deploying using the Helm chart, I noticed that it stays at 0/1 Pods ready.

NAME                                            READY   STATUS    RESTARTS   AGE
gitlab-ci-pipelines-exporter-755cf64984-jkk9q   0/1     Running   0          7s

When I check the logs, it shows that the exporter is polling the projects correctly.  

I have increased the timing of the liveness probe but that didn't seem to help. Any idea what could be wrong?

Thank you.

**Comment by mvisonneau** [comment]
👋 hey @adeadeabodunrin, are you using gitlab.com or a self hosted endpoint?

**Comment by adeadeabodunrin** [comment]
Thanks a lot for your help! Am using a self hosted gitlab.

**Comment by mvisonneau** [comment]
On a self hosted cluster/instance, you need to point the health_url to your [health endpoint](https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html) to get it to work correctly:

```yaml
gitlab:
  url: https://git.my.corp
  health_url: 'https://git.my.corp/-/liveness?token=xxxxx'
```

**Comment by adeadeabodunrin** [comment]
Thanks a lot. This appeared to work.
