### ISSUE TITLE
No data loaded after import - GitLab Grafana

### ISSUE THREAD

**Issue by emucker** [mvisonneau/gitlab-ci-pipelines-exporter#116]
Thanks for creating this project.  I was able to successfully deploy the project with docker-compose and connect to my local GitLab server with a token.  What I really need to do is import the dashboard into the integrated Grafana server in GitLab and access the information directly.  I have successfully imported the dashboard, however, the pipeline statuses do not pull any data.  I have default prometheus data source configured (localhost:9090).  I'm new to Prometheus/Grafana so I'm probably missing a configuration step for this use case.  Also, I cannot find the code in the project that is handling the actual calls to the APIs for the defined metrics.  any assistance would be appreciated.

**Comment by mvisonneau** [comment]
Hi @emucker! Thanks for the feedback :) 

At first sight, I unfortunately don't know what can be wrong with your embedded prometheus/grafana setup embeded in GitLab.

**Comment by emucker** [comment]
After spending some time working with the project, my assumptions are that this requires the minimum configured on the GitLab server:
1. gitlab-ci-pipelines-explorer docker container deployed and running on server
2. prometheus configured to scrape gitlab-ci-pipelines-explorer
3. gitlab-ci-pipelines-explorer dashboard imported into grafana

Are these correct assumptions?  Also, the default port for the gitlab-ci-pipelines-explorer docker container is 8080.  This conflicts with GitLab services on the server.  To change the port, can I simply change the exposed port in the Dockerfile and update the port in the docker-compose file?  I tried to simply run the container image pointed to a random port, but this did not work.  I've played around with the command line binary and see it has an option to specify a listening port and address.

Thanks for any additional information you can provide.  I've been working to create a dashboard to pull similar metrics using direct queries from the Postgresql database.  This has been a good learning exercise.

**Comment by emucker** [comment]
Another question regarding wildcards.  Is there an option I can provide in the config file to have the wildcards recurse all sub-groups in a parent group?

**Comment by mvisonneau** [comment]
>  my assumptions are that this requires the minimum configured on the GitLab server:
    1. gitlab-ci-pipelines-explorer docker container deployed and running on server
    2. prometheus configured to scrape gitlab-ci-pipelines-explorer
    3. gitlab-ci-pipelines-explorer dashboard imported into grafana

yes!

>  To change the port, can I simply change the exposed port in the Dockerfile and update the port in the docker-compose file?

yes! You also need to set the `--listen-address` flag to make the binary listen onto a different port.

> Another question regarding wildcards. Is there an option I can provide in the config file to have the wildcards recurse all sub-groups in a parent group?

yes, you can use the following:

```yaml
wildcards:
  - owner:
      name: foo
      kind: group
      include_subgroups: true
```

**Comment by mvisonneau** [comment]
I will close this issue as it seems to be quite solved!
