### ISSUE TITLE
Increased time between project polls without pipeline

### ISSUE THREAD

**Issue by Asvor** [mvisonneau/gitlab-ci-pipelines-exporter#12]
Needs mechanism of asking old branch without pipelines with double delay ( based at previous asking)
If we see that "Could not find any pipeline for ***", we do 3 research and if it fails we do double-time between the asking for the branch.
Because now we have an extreme load of the server if we have many projects.

Thanks for your project)

**Comment by mvisonneau** [comment]
👋 thanks for the feedback @Asvor! That is definitely a good idea. I will have a look into it.

**Comment by mvisonneau** [comment]
I implemented this feature in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/c39c0c8566440a9a41ba8eb159091c4eb6439dc4

**Comment by mvisonneau** [comment]
Released in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.2.5 :) feel free to reopen if it doesn't work as expected!
