### ISSUE TITLE
Pipeline Build Metrics

### ISSUE THREAD

**Issue by edthezombie** [mvisonneau/gitlab-ci-pipelines-exporter#122]
Hello,

Thank you for creating this great project. We are using it already but are wondering if we can get the below data out somehow?

Number of builds
Number of failed vs. successful builds
Average Build Time per Branch/per job

Or just in general, is there anyway to customize the data we can get out? Thank you in advance.

**Comment by mvisonneau** [comment]
Thank you for the kind feedback @edthezombie!

> Number of builds
You should already be able to have the number of build through the `gitlab_ci_pipeline_run_count` metric

> Number of failed vs. successful builds
There is no metric for that but perhaps you could correlate it from the `gitlab_ci_pipeline_last_job_run_status` metric with some effort 🤔 

> Average Build Time per Branch/per job
You should be able to get it using `gitlab_ci_pipeline_last_run_duration_seconds`

I assume that prometheus allows you to manipulate the metrics to make it fit your need

**Comment by mvisonneau** [comment]
I will close this issue as I believe to have covered your questions. Feel free to reopen if doubts are remaining!
