### ISSUE TITLE
Running the project against private GitLab without certificate gives SSL error. 

### ISSUE THREAD

**Issue by fog1985** [mvisonneau/gitlab-ci-pipelines-exporter#124]
Hi guys, 
We have our own GitLab server and it has internal addressing and no real certificates for https access. 
Hence I am getting SSL error due to not a trusted certificate. 
Is there any way to bypass this limitation?

Here what I get after checking logs:
```
docker logs -f example_gitlab-ci-pipelines-exporter_1

time="2020-06-25T14:48:23Z" level=error msg="getting project by name" error="Get \"https://gitlab.own/api/v4/projects/bde%2Fproject-name\": x509: certificate signed by unknown authority" project-name=sub/project-name
```

**Comment by mvisonneau** [comment]
:wave: hey @fog1985,

I reckon you have 2 options:
- Import your CA onto the container in `/etc/ssl/certs`
- Disable SSL verification in the [configuration file](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/docs/configuration_syntax.md) : `gitlab.disable_tls_verify: true`

**Comment by fog1985** [comment]
Hey @mvisonneau ,
Thank you for such s prompt reply. :)
SSL thing is fixed now. No errors in the logs.
But no result as well:
```
time="2020-06-26T07:40:13Z" level=info msg="starting exporter" discover-projects-refs-interval=300s discover-wildcard-projects-interval=1800s gitlab-endpoint="https://gitlab.own" on-init-fetch-refs-from-pipelines=false polling-projects-refs-interval=30s polling-workers=6 rate-limit=10rps
time="2020-06-26T07:40:13Z" level=info msg="started, now serving requests" listen-address=":8080"
time="2020-06-26T07:40:13Z" level=info msg="discover wildcards" total=0
time="2020-06-26T07:40:16Z" level=info msg="polling metrics from projects refs" total=0
time="2020-06-26T07:40:43Z" level=info msg="polling metrics from projects refs" total=0
```
So it finds the project, it has all permissions based on `access token` provided. But nothing at the end. 
By the way, in addition to `read_repository` it also requests for `api` one access type.

Any thoughts on what might be the issue? Why it just doesn't get anything?
Once I go to the metrics via browser I get as follow:
```
# HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp metric handler.
# TYPE promhttp_metric_handler_errors_total counter
promhttp_metric_handler_errors_total{cause="encoding"} 0
promhttp_metric_handler_errors_total{cause="gathering"} 0
```

**Comment by fog1985** [comment]
Hey. I have found the issue: `refs_regexp: "^.*$"` did the trick and all started working. :)
I got 1 more question @mvisonneau , is it possible to get an error message from the failing GitLab's pipeline? 
Like the reason why it's failed. That would be just awesome if it's supported by your solution. :)

**Comment by mvisonneau** [comment]
great! unfortunately the GitLab API do not return such information, I reckon it would be quite hacky to implement.

**Comment by fog1985** [comment]
I see. Well. Thanks for your reply @mvisonneau .
Maybe you can assist with Improving the Grafana table a little bit? :)
It returns all the needed stuff. I am trying to make cells in a table clickable. And to be sent to GitLab's pipeline they stand for.
The table in context is the one that shows "healthy" runs. I believe the same would be nice to have for failed ones. 
As there is no way of getting the error message that would be beneficial just click on the row(cell) in a table and be redirected to GitLab's pipeline. 
As there is `gitlab_ci_pipeline_last_run_id` present I think it should be possible. Though I could not manage to integrate it yet in present logic and set-up of Grafana (I am using example stack for playing around). :)
I will keep trying. Any hint on how to implement/extend it will be much appreciated. :)

**Comment by mvisonneau** [comment]
👋 hey! Regarding your Grafana related question, I apologise but I am not planning to provide support on how to make it better but contributions over my example are very welcome! Taking the time to figure out your usecase would probably lead me towards the Grafana and Prometheus documentations and some googling :)

I am going to close this issue as your TLS question is sorted.

**Comment by fog1985** [comment]
> 👋 hey! Regarding your Grafana related question, I apologise but I am not planning to provide support on how to make it better but contributions over my example are very welcome! Taking the time to figure out your usecase would probably lead me towards the Grafana and Prometheus documentations and some googling :)
> 
> I am going to close this issue as your TLS question is sorted.

Fair enough, man. :)
Thank you for the work you have done with this solution. And I will go googling and reading more docs ))

Kindest regards,
Taras.

**Comment by Sudeep1998** [comment]
Hey @fog1985 
How did you solve this  issue. I am attaching the error which I am getting in the browser localhost:8080/metrics.
![image](https://user-images.githubusercontent.com/34943644/118002755-8fc42f80-b365-11eb-8e79-c01ca34f699c.png)

The journal logs says the project is getting discovered.

![image](https://user-images.githubusercontent.com/34943644/118003079-dca80600-b365-11eb-9f4f-83d6ba473fde.png)

My  gitlab-ci-pipelines-exporter.yml is as:

![image](https://user-images.githubusercontent.com/34943644/118003641-622bb600-b366-11eb-8e4c-3ccb0be875d2.png)

**Comment by fog1985** [comment]
> Hey @fog1985
> How did you solve this issue. I am attaching the error which I am getting in the browser localhost:8080/metrics.
> ![image](https://user-images.githubusercontent.com/34943644/118002755-8fc42f80-b365-11eb-8e79-c01ca34f699c.png)
> 
> The journal logs says the project is getting discovered.
> 
> ![image](https://user-images.githubusercontent.com/34943644/118003079-dca80600-b365-11eb-9f4f-83d6ba473fde.png)
> 
> My gitlab-ci-pipelines-exporter.yml is as:
> 
> ![image](https://user-images.githubusercontent.com/34943644/118003641-622bb600-b366-11eb-8e4c-3ccb0be875d2.png)

Hey @Sudeep1998 ,
Really don't remember from the top of my head. I will try to have a look and find the config file I had finally came up with. 
If I find anything worthy to be shared I will let you know.

**Comment by Sudeep1998** [comment]
@fog1985 @mvisonneau When I remove wildcards and mention the project explicitly , it works. But when I broaden the scope I get that error. The token which I am using having access to thousands of projects.
Is there any limitation in using this exporter or do i need to mention something in the yaml file ?

**Comment by mvisonneau** [comment]
@Sudeep1998 are those couple metrics the only one you get from `127.0.0.1:8080/metrics` ? :thinking:

**Comment by Sudeep1998** [comment]
@mvisonneau @fog1985. 
When I put a wildcard in the yml file I get only those two records. But when I remove the wildcard keys and provide fewer project name  I get much detailed records along with this two record.

**Comment by mvisonneau** [comment]
@Sudeep1998, it might be related to #276, lets follow-up in there
