### ISSUE TITLE
Expose gitlab runner description for jobs

### ISSUE THREAD

**Issue by rpocase** [mvisonneau/gitlab-ci-pipelines-exporter#126]
In addition to the metrics provided by `fetch_pipeline_job_metric: true`, I would like to be able to capture which gitlab runner was used. E.g., for a job below, I would set a runner label equal to `runner.description` of the job.

```
  ...
  "runner": {
    "id": 12,
    "description": "MY_RUNNER",
    "ip_address": "1.2.3.4",
    "active": true,
    "is_shared": true,
    "name": "gitlab-runner",
    "online": true,
    "status": "online"
  },
  ...
```

```
gitlab_ci_pipeline_last_job_run_status{job="build",project="bar/project",ref="master",stage="build",status="failed",topics="",runner="MY_RUNNER"} 0
```

There is a risk here is in terms of label explosion, especially for autoscaled runners. I would suggest guarding against this through having a runner name normalization option. E.g. `fetch_pipeline_runner_metric.runner_regex: (auto-scale)-.+` would set a runner label equal to `auto-scale`).

**Comment by mvisonneau** [comment]
very good idea @rpocase!
