### ISSUE TITLE
Option to disable valid cert check

### ISSUE THREAD

**Issue by bbung** [mvisonneau/gitlab-ci-pipelines-exporter#13]
Hi,

my gitlab instance does not have a valid cert (aka self-signed). Is there a way to disable the valid cert check?

I tried using the docker image and got the following error

 Unable to fetch project xxx/xxx' from the GitLab API : Get https://git/api/v4/projects/xxx%2Fxxx: x509: certificate signed by unknown authority

Any help would be appreciated.

Thanks
Björn

**Comment by mvisonneau** [comment]
Hey @bbung, thanks!

I just added the feature in this commit : https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/0533d03ba6d1251105fcb86cf5d95c9e76843bc1 

It will be built in the next release but you should be able to benefit from it if you use the `latest` tag of the docker image.

I haven't been able to test so feel free to reopen if it doesn't work.

**Comment by mvisonneau** [comment]
You need to set :

**Comment by mvisonneau** [comment]
You need to set :

```yaml
gitlab:
  skip_tls_verify: true

**Comment by bbung** [comment]
Wow, amazingly fast and it works!

Thank you very much!
