### ISSUE TITLE
Checksum mismatch in go.sum

### ISSUE THREAD

**Issue by mmahut** [mvisonneau/gitlab-ci-pipelines-exporter#14]
Looks like one of the imports have broken checksum.

```panic: Error processing import path "github.com/hashicorp/vault/sdk": Bad SHA256 for repo https://github.com/hashicorp/vault with rev v0.1.11```

**Comment by mvisonneau** [comment]
Which command / how did you do/use to end up with this error ?

**Comment by mvisonneau** [comment]
I haven't been able to reproduce, starting from a empty go environment 🤔

**Comment by mmahut** [comment]
I'm using ```vgo2nix``` to build it, does your build process checks the checksums?

Just try to run vgo2nix in the dir.

https://github.com/adisbladis/vgo2nix

**Comment by mvisonneau** [comment]
Indeed I seem to had quite some mess in the `go.(mod|sum)` files. Should be better with https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/34034112c0b3df777ee1c85630dc2b589ff68d90

I wasn't able to test with your tool though, did not have time to investigate it further: 

```
panic: Error processing import path "github.com/julienschmidt/httprouter": exec: "nix-prefetch-git": executable file not found in $PATH

goroutine 1 [running]:
main.main()
```

Let me know if it's better for you!

**Comment by mvisonneau** [comment]
Feel free to reopoen if it still doesn't work for you!

**Comment by mmahut** [comment]
It works, thanks!
