### ISSUE TITLE
grafana-polystat-panel is coming vertically instead of horizontally...  

### ISSUE THREAD

**Issue by tanmoyrsc** [mvisonneau/gitlab-ci-pipelines-exporter#144]
Hi,

Instead on coming sideways polystat-panel coming vertically, that's why most of the hexagon are placed out of screen and not visible. is there any solution for that?

thanks in advance

Br,
Tanmoy

**Comment by mvisonneau** [comment]
👋 hi @tanmoyrsc,

I believe this is something worth raising on https://github.com/grafana/grafana-polystat-panel/issues instead as I have no context/idea about what your issue with this specific plugin could be, sorry about that!
