### ISSUE TITLE
Add reference URL to GitLab pipeline efficiency docs

### ISSUE THREAD

**Issue by dnsmichi** [mvisonneau/gitlab-ci-pipelines-exporter#145]
Hi @mvisonneau, 

this magnificent exporter is now highlighted in our pipeline efficiency docs.

https://docs.gitlab.com/ee/ci/pipelines/pipeline_efficiency.html

I'm not sure where to link it in the README, hence my question before creating a PR :) Feel free to go ahead as well.

**Comment by mvisonneau** [comment]
whoa, thanks @dnsmichi and others who put trust in this tool! 🙇 🙏 I managed to find some space to reference it in the README 😄
