### ISSUE TITLE
Poll all projects the token gives access to

### ISSUE THREAD

**Issue by mfriedenhagen** [mvisonneau/gitlab-ci-pipelines-exporter#146]
* We have an internal instance of GitLab-CI and want to provide reporting based on Prometheus.
* We got ca. 300 groups and 6000 projects in GitLab
* Instead of having each group setting up and configuring it's own gitlab-ci-pipelines-exporter we thought about defining a tool account which groups could add as reporter and which could then gather the pipeline status.
* This would allow more control about the poll frequency to avoid trashing the instance as well as spare teams/groups the burden to setup the exporter themselves (using the defaults it would take > 10 minutes to walk all projects).
* Alternatively we would need to create an automation for creating the config.yml ourselves and add/delete wildcards.

**Comment by mvisonneau** [comment]
👋 hey @mfriedenhagen, polling all projects accessible by the token is possible using an empty wildcard:

```yaml
wildcards:
  - {}
```

I updated the doc to make it clearer :)

**Comment by mfriedenhagen** [comment]
Thanks @mvisonneau
