### ISSUE TITLE
Allow notification of pipeline events

### ISSUE THREAD

**Issue by mfriedenhagen** [mvisonneau/gitlab-ci-pipelines-exporter#147]
* As outlined in #146 we have a GitLab instance with 228 groups and 6000 projects.
* I thought about a mechanism in the gitlab-ci-pipelines-exporter which receives pipeline events via webhook (https://gitlab.com/help/user/project/integrations/webhooks.md#pipeline-events) instead of polling.
* So the gitlab-ci-pipelines-exporter would just be used to store the state instead of polling itself.
* Of course this could be somehow implemented with the push_gateway, but doing it in this exporter would allow 
to reuse metrics names more easily.

**Comment by mvisonneau** [comment]
👋 hey @mfriedenhagen, thanks for sharing your usecase and suggestion. I believe this is a tremendeous idea! I'll try to put some more thoughts into it but I am very keen to move towards a push based approach as well.

**Comment by mvisonneau** [comment]
@mfriedenhagen, I spent a good time working on this feature this week and am happy to announce it is now part of the [0.4.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.0) release! Hope you will be able to implement it and let us know how it goes! :)

**Comment by mfriedenhagen** [comment]
Thank you very much, @mvisonneau I will definitely report back, though I am not sure I will get to it this week.
