### ISSUE TITLE
"Last Run" hyperlink to gitlab pipeline build 

### ISSUE THREAD

**Issue by scott-au** [mvisonneau/gitlab-ci-pipelines-exporter#15]
is there any mechanism to add links to view gitlab individual pipeline runs   - either the ref or last run column ?

**Comment by mvisonneau** [comment]
👋 hey @scott-au, good idea! I added this metric in this commit : https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/923338aa34d89083b05d520c7e6b09c994029c35

**Comment by mvisonneau** [comment]
Released in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.2.5 !

**Comment by scott-au** [comment]
that was quick!!

@mvisonneau  is there any extra config needed ? using the docker compose from the /example and pulling :latest doesnt seem to have any links - from the change it looks like it should be in the last run column ?

any advice ?

**Comment by mvisonneau** [comment]
hmm 🤔 I just tested and managed to get the new metric correctly. 

```
~$ docker run -d --rm -v $(pwd):/opt -p 8080:8080 mvisonneau/gitlab-ci-pipelines-exporter:latest -c /opt/config.yml
~$ curl -s localhost:8080/metrics | grep gitlab_ci_pipeline_last_run_id
# HELP gitlab_ci_pipeline_last_run_id ID of the most recent pipeline
# TYPE gitlab_ci_pipeline_last_run_id gauge
gitlab_ci_pipeline_last_run_id{project="foo",ref="bar"} 2.2774739e+07
```

**Comment by scott-au** [comment]
thanks @mvisonneau  looks like we are pulling the latest binary.. do we need to also add reference to gitlab_ci_pipeline_last_run_id into example/grafana/dashboard.json  to be able to view this metric ? i cant see any reference to it in there

**Comment by mvisonneau** [comment]
I haven't updated it in the dashboard indeed. PR or issue welcome! :)
