### ISSUE TITLE
gitlab_ci_pipeline_time_since_last_run_seconds not updated, when ref was deleted

### ISSUE THREAD

**Issue by krebs-GVL** [mvisonneau/gitlab-ci-pipelines-exporter#150]
Hi,

This may be the same as #119 
I realized, that `gitlab_ci_pipeline_time_since_last_run_seconds` will not get updated for merge request pipelines, if the merge request was deleted. I expect, that this also happens with branch refs.

I can only provide a screenshot from a custom dashboard

![grafik](https://user-images.githubusercontent.com/47516218/95296112-80817e80-0878-11eb-95c2-342d968b7b3e.png)

It is sorted by ID, so the most recent is on top. The eternal branches `develop` and `master` shows the correct values, but the merge request refs shows the exact time it took from pipeline completion to merge/delete.

Maybe a timestamp instead of a duration is more reliable?

**Comment by mvisonneau** [comment]
👋 hey @krebs-GVL, indeed, this is something that I wanted to do for a while, I just pushed it as part of a broader metric naming update (b5d2f65). It will be part the next release. You will therefore be able to use `time() - gitlab_ci_pipeline_timestamp` to compute the value dynamically in prometheus.

**Comment by mvisonneau** [comment]
👋 hey @krebs-GVL, indeed, this is something that I wanted to do for a while, I just pushed it as part of a broader metric naming update (26ddfe8). It will be part the next release. You will therefore be able to use time() - gitlab_ci_pipeline_timestamp to compute the value dynamically in prometheus.

**Comment by mvisonneau** [comment]
These changes are part of the [0.4.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.0) release!
