### ISSUE TITLE
Integration with Influxdb

### ISSUE THREAD

**Issue by brucec64** [mvisonneau/gitlab-ci-pipelines-exporter#156]
Is it currently possible to integrate the gitlab-ci-pipelines-exporter with Influxdb instead of Prometheus?

**Comment by mvisonneau** [comment]
👋 hey @brucec64, it is not tailored to support InfluxDB unfortunately. However, it looks like you may be able to get it to work using this experimental feature : https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/
