### ISSUE TITLE
add status for when pipeline is  "status": "manual"

### ISSUE THREAD

**Issue by scott-au** [mvisonneau/gitlab-ci-pipelines-exporter#16]
currently we can see status for: running, passed, failed - and different colouring for these statuses in the status Column

would it makes sense to add status for manual stages ? 

it will return  "status": "manual" in api/v4/projects/:id/pipelines. in UI would display as

![image](https://user-images.githubusercontent.com/46589110/64215389-d0fd0e80-cef7-11e9-9ef0-afb226a2b695.png)

currently we can see on dash:
![image](https://user-images.githubusercontent.com/46589110/64215434-1f121200-cef8-11e9-972b-221e68ddc42c.png)

**Comment by scott-au** [comment]
possible pipeline statuses: running, pending, success, failed, canceled, skipped 

(from https://docs.gitlab.com/ee/api/pipelines.html)

**Comment by mvisonneau** [comment]
Indeed, I added the missing statuses in this commit. https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/33c481d42b959cb25a8c6123af98b01299fec223

Not sure how hard it will be to get them to show correctly in GitLab though.
