### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by Antiarchitect** [mvisonneau/gitlab-ci-pipelines-exporter#178]
1. Is there any way (or plans) to have job_id level of granularity for the duration? My case is I'm trying to analyze bottlenecks in our CI pipelines so I need to be able to get the duration of each job individually to properly group and count.
2. Seems like there is no respect for Grafana time range for this dashboard at least: https://grafana.com/grafana/dashboards/13328 is it planned? For now it seems to me I see all the branches I ever had no matter of last pipeline execution time. My scale is ~2k pipelines, ~100 branches, and each pipeline has 50-60 jobs to run - that is one project.
3. It f**cks my GitLab till death when I try to open refs regex to ".*" but hope lowering the `maximum_gitlab_api_requests_per_second` will do the trick

BTW the project is awesome, thank you!

**Comment by mkrvanton** [comment]
@Antiarchitect the same pain with Gitlab performance when gitlab-ci-pipelines-exporter is running :(
![image](https://user-images.githubusercontent.com/66248227/98557897-1019b300-22a5-11eb-9aed-fc432f8fd1bb.png)

**Comment by mvisonneau** [comment]
👋 hey guys

`1` - I did not plan on adding the `job_id` as a label yet but this could be discussed
`2` - Indeed, the dashboards list all monitored jobs, pipelines, environments independently of the timeframe, if you which to scope it down, please use the variables to narrow down the search. AFAIK the table panels does not behave well with timeframing so they use instant/most recent vectors. I do not plan on updating this implementation any time soon but contributions are welcome :)
`3` - definitely lower down your `maximum_gitlab_api_requests_per_second` value or switch to a push based approach if this is not good enough : https://github.com/mvisonneau/gitlab-ci-pipelines-exporter#push-based-implementation-leveraging-gitlab-webhooks

**Comment by mkrvanton** [comment]
@mvisonneau Hi :) thanks, I missed it, I'll try the push-based approach
