### ISSUE TITLE
Scrape git submodules

### ISSUE THREAD

**Issue by vakaobr** [mvisonneau/gitlab-ci-pipelines-exporter#18]
Hello there,

A idea (don't know how hard its to implement it): Possibility to scrape all subprojects inside a project.

In my company we have a hosted gitlab, used by multiple teams, and each one has your own project, and inside this, we create our subprojects to work. But, to use the scrapper like it is (and like our structure is) is needed to add manually all subprojects since just can scan by user or group.

**Comment by kadrach** [comment]
The patch below enables scraping of subgroups, as well as scraping "all" projects by default. Note that on our hosted installation of gitlab this directly leads to "too many open files" failures, some sort of queueing and backoff is probably required here, have not looked at this in detail.

```diff
diff --git a/cmd/config.go b/cmd/config.go
index 8340e10..460ced5 100644
--- a/cmd/config.go
+++ b/cmd/config.go
@@ -35,8 +35,9 @@ type Project struct {
 type Wildcard struct {
 	Search string
 	Owner  struct {
-		Name string
-		Kind string
+		Name             string
+		Kind             string
+		IncludeSubgroups bool `yaml:"include_subgroups"`
 	}
 	Refs string
 }
diff --git a/cmd/gitlab.go b/cmd/gitlab.go
index f3b9b3e..e720f85 100644
--- a/cmd/gitlab.go
+++ b/cmd/gitlab.go
@@ -66,6 +66,7 @@ func (c *Client) listProjects(w *Wildcard) ([]Project, error) {
 			gps, resp, err = c.Groups.ListGroupProjects(
 				w.Owner.Name,
 				&gitlab.ListGroupProjectsOptions{
+					IncludeSubgroups: &w.Owner.IncludeSubgroups,
 					ListOptions: listOptions,
 					Archived:    &falseVal,
 					Simple:      &trueVal,
@@ -73,7 +74,14 @@ func (c *Client) listProjects(w *Wildcard) ([]Project, error) {
 				},
 			)
 		default:
-			return projects, fmt.Errorf("Invalid owner kind '%s' must be either 'user' or 'group'", w.Owner.Kind)
+			gps, resp, err = c.Projects.ListProjects(
+				&gitlab.ListProjectsOptions{
+					ListOptions: listOptions,
+					Archived:    &falseVal,
+					Simple:      &trueVal,
+					Search:      &w.Search,
+				},
+			)
 		}
 
 		if err != nil {
```

**Comment by mvisonneau** [comment]
From what I understood of @vakaobr request, he wants the ability to automaticall discover `submodules` within projects. This is going to be quite challenging to implement as this would imply fetching the necessary git content of the repository and then parse it. I do not plan to work on this myself but PRs are welcome.

On the other end, thanks for the patch @kadrach, I'll try to implement it!

**Comment by mvisonneau** [comment]
done in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/bace58413262c32d22430fa5d73acb84904f57fc

thanks again @kadrach 🙏

**Comment by vakaobr** [comment]
hooray!

**Comment by toniiiik** [comment]
good job but... 

There is wrong property name in README.md config.yml
` includeSubgroups: true`
must be
` include_subgroups: true`

**Comment by mvisonneau** [comment]
README.md has been fixed since and we do not have it as part of the example config.yml anymore, thanks for the info @toniiiik.

I will close this issue as I reckon that you can probably workaround it by playing with `wildcards`.
