### ISSUE TITLE
Question: How to hide/ignore pipeline statuses that are older than x weeks?

### ISSUE THREAD

**Issue by dbluxo** [mvisonneau/gitlab-ci-pipelines-exporter#189]
Hi @mvisonneau,

Thanks for this exporter!

Is there a way to hide/ignore pipeline statuses that are older than x days/weeks? (e.g. 4 weeks)

Best regards,

Daniel.

**Comment by mvisonneau** [comment]
👋 hey @dbluxo, thanks for the kind feedback 🙇 

Are you looking to hide them at the exporter layer or at the visualization one (eg: Prometheus/Grafana)?

**Comment by dbluxo** [comment]
> Are you looking to hide them at the exporter layer or at the visualization one (eg: Prometheus/Grafana)?

At the exporter layer

**Comment by mvisonneau** [comment]
Ok, well I am afraid there is no such capabilities yet but I am assuming it wouldn't be too complicated to implement.

**Comment by mvisonneau** [comment]
@dbluxo I just implemented a new parameter to allow you to do so, l

**Comment by mvisonneau** [comment]
It has now been released as part of v0.4.5! Feel free to reopen if I missed some bits! 🙇

**Comment by dbluxo** [comment]
Awesome, thanks! At first view it works great!
