### ISSUE TITLE
Dashboard changes

### ISSUE THREAD

**Issue by vakaobr** [mvisonneau/gitlab-ci-pipelines-exporter#19]
Hello there!

I did some "tunning" on the dashboard and want to share it with you to check if its useful to merge on code or not.

I've uploaded the .json at [this gist](https://gist.github.com/vakaobr/b82f3dee2a7465ca96dbd0b46b6ca795) and just need to change `MYAWESOMEGITLABURL` by your gitlab URL and check it.

Changes are (which I remember by now):

- Added a clock plugin (that its on our monitoring display and its kinda useful to remember time of daily standup)
- Added a column saying the latest id of each pipeline
- Separated running pipelines to a different table
- Added links to pipelines (and on healthy table, the link leads to latest pipeline)

**Comment by mvisonneau** [comment]
Thanks for the enhancements @vakaobr. Would you mind getting an publicly exportable version of the dashboard to make it easier for us to reuse ?

https://grafana.com/docs/reference/export_import/

**Comment by vakaobr** [comment]
Hello there,

Public exportable .json format uploaded to [this gist](https://gist.github.com/vakaobr/04d0bd9a8c17d9687643d61bc23a81de)

**Comment by mvisonneau** [comment]
@vakaobr apologies for the late feedback on this one, I recently updated the dashboards and added new ones following the recent metric updates which I made. It supersedes most of your suggestions except the clock plugin. I reckon we can therefore close this issue! Thanks again!
