### ISSUE TITLE
Using exported metrics to autoscale runner managers

### ISSUE THREAD

**Issue by knkarthik** [mvisonneau/gitlab-ci-pipelines-exporter#193]
@mvisonneau  Thank you so much for this wonderful piece of work! 🏆 

I'm using gitlab k8s executor and trying to find a way to autoscale runner manger pods depending on the the number of pending jobs (not sure if there are better ways, but this has worked for us in the past although via a cron job).

Since gitlab runner [supports HPA](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/0-23-0-stable/values.yaml#L435) I imaging I could leverage that. 

Do you have any insights?

**Comment by mvisonneau** [comment]
👋 hey @knkarthik, thanks for the kind feedback.

I think you could leverage the metrics being exported from the runner pods themselves if you need to autoscale their amount: https://docs.gitlab.com/runner/monitoring/#available-metrics.

But I am not sure why you would need to autoscale them, they consume almost no CPU and ~16MB of RAM each 🤔

**Comment by knkarthik** [comment]
@mvisonneau 
> But I am not sure why you would need to autoscale them, they consume almost no CPU and ~16MB of RAM each 🤔

I want to scale up them so that my jobs won't be in pending state waiting to be picked up by a runner. Currently I've 1 runner that can handle 10 jobs but the 11th job would have to wait. I could set a high job concurrency in runner settings but I don't want to over-provision.

You are right in that I could use https://docs.gitlab.com/runner/monitoring/#available-metrics but to me scaling based on the number of pending jobs makes more sense than scaling based on the current number of running jobs (which is exposed by gitlab).

I guess I've to expose metrics to custom/external metrics endpoint using [k8s-prometheus-adapter ](https://github.com/directxman12/k8s-prometheus-adapter)or [kube-metrics-adapter](https://github.com/zalando-incubator/kube-metrics-adapter) if I'm not mistaken.

**Comment by mvisonneau** [comment]
I am not sure if there is a hard limit on how many concurrent jobs a single k8s based gitlab-runner can schedule. Although for me updating this value does not imply any kind of compute resources provisioning. You are only limited by the capacity of your k8s cluster.

**Comment by knkarthik** [comment]
May be I didn't explain this properly. I've 1 runner pod than can pick up 10 jobs. Now if I've 50 jobs in gitlab 40 of them would be pending. If this happens I want to scale to 4 pods. So HPA based not on resource use but on custom metric like number of pending jobs.

**Comment by mvisonneau** [comment]
Yes but I am fairly convinced that configuring your gitlab-runner pod to run 50 jobs concurrently would not have any "overprovisioning" impact :)

**Comment by mvisonneau** [comment]
I will close this as I believe it is possible to achieve this even though it is probably not necessary! If someone wants to provide a more detailed answer feel free to!
