### ISSUE TITLE
Prometeus query

### ISSUE THREAD

**Issue by Sakojpa** [mvisonneau/gitlab-ci-pipelines-exporter#2]
Hi! How do you query prometeus for status panel?

**Comment by mvisonneau** [comment]
it is a bit of hack but I basically create a variable based on all projects with the following :repeat on the

**Comment by mvisonneau** [comment]
It's a bit of a hack but I started by creating a dasboard variable that lists all the projects : 
`project` = `label_values(gitlab_ci_pipeline_last_run_duration_seconds, project)`
And then do a *repeat* of a singlestat panel with the following query :
```
sum(gitlab_ci_pipeline_status{project=~"$project",status=~"success"}) + sum( gitlab_ci_pipeline_status{project=~"$project",status=~"running"} * 2 )
```
For the colorization, the valueMap is the following :
```
0 = NOK
1 = OK
2 = RUNNING
```
