### ISSUE TITLE
Use behind http proxy

### ISSUE THREAD

**Issue by ardole** [mvisonneau/gitlab-ci-pipelines-exporter#212]
Hi @mvisonneau 

I am not able to use your exporter behind a corporate http proxy.

Have you got any information to give about that ?

I'm not an expert on Go :( As I understand it uses the standard go client, from https://github.com/xanzy/go-gitlab/blob/master/gitlab.go and https://github.com/hashicorp/go-cleanhttp/blob/master/cleanhttp.go ? so the system environment variables are expected to be used ? as described here https://golang.org/pkg/net/http/#ProxyFromEnvironment

I tried:
export http_proxy=ip:port
export https_proxy=ip:port
export HTTP_PROXY=ip:port
export HTTPS_PROXY=ip:port
and also:
export http_proxy=http://ip:port
export https_proxy=http://ip:port
export HTTP_PROXY=http://ip:port
export HTTPS_PROXY=http://ip:port

But impossible to get it working. (on Centos 7 and also in Redhat 7)

**Comment by mvisonneau** [comment]
👋 hey @ardole,

Thanks for raising this up, indeed the configuration of the client was missing in order to make it leverage those env variables. I have pushed a fix: ca4ca0e, it will be part of the next release!

**Comment by ardole** [comment]
Thanks, tested, it works well 👍

**Comment by mvisonneau** [comment]
just got released as part of [v0.4.7](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.4.7), closing the issue!
