### ISSUE TITLE
Question about the link of ID at Grafana

### ISSUE THREAD

**Issue by dalpengholic** [mvisonneau/gitlab-ci-pipelines-exporter#213]
Hello, Maxime.

First of all, thank you for this wonderful project. I just tested the latest version and it is much nicer than last October 
The reason I created this issue because I was not sure my observation came from error or just my incorrect configuration.

1.
What I did:
- Basically, I followed the your quickstart README.
- I modified `config.yml` in gitlab-ci-pipelines-exporter folder
- I changed gitlab url and token values and I set to use wildcard to collect repositories. For example, `url: mygitlab.com`

What has happened:
- Successfully read repositories and the result is being shown by Grafana.
- When I place cursor on ID to check the link of an ID, the link starts like `https://gitlab.com` not `https://mygitlab.com`
- So, when I click any id, it redirect me to gitlab.com.

Would you help me how to resolve this?

2.
BTW, what is this message and how to remove it?
`gitlab-ci-pipelines-exporter_1  | time="2021-01-14T10:38:05Z" level=debug msg="throttled GitLab requests" for=1.73131438s`

Thanks a lot.

**Comment by mvisonneau** [comment]
👋 Thanks for the kind feedback @dalpengholic! 🙇 

> When I place cursor on ID to check the link of an ID, the link starts like https://gitlab.com not https://mygitlab.com

You need to configure the `GITLAB_HOST` variable in the dashboard settings which defaults to `gitlab.com`

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1761583/104623546-654db880-568a-11eb-8fcb-9b26bd32672e.png">

> BTW, what is this message and how to remove it?

This means you are attempting to make more requests per seconds than the [maximum allowed in the config](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md) (default to 10)

You can sort this out by increasing the value or by [leveraging a push based approach with webhooks](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/tree/main/examples/webhooks):

```yaml
pull:
  maximum_gitlab_api_requests_per_second: x
```

hope this helps, feel free to reopen if necessary!

**Comment by dalpengholic** [comment]
Thank you so much. 
May I add this info to /examples/quickstart/README.md and make pull request?

**Comment by mvisonneau** [comment]
of course feel free to @dalpengholic 🙏

**Comment by stars693** [comment]
Hello @mvisonneau ,

In my case, the dashboards are downloaded from Grafana Labs. On the dashboard, it is not resolving the GITLAB_HOST variable which is set as ${VAR_GITLAB_HOST}.

![image](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/33175562/fcdd5640-8248-4cd5-aa52-4ce8e7b6e9e1)

I am unable to update its value permanently from UI as it gives me following message

> "This dashboard cannot be saved from the Grafana UI because it has been provisioned from another source. Copy the JSON or save it to a file below, then you can update your dashboard in the provisioning source."  

Can you please guide where can I define this variable value ?
