### ISSUE TITLE
json: cannot unmarshal array into Go value of type gitlab.Project

### ISSUE THREAD

**Issue by udaymadu** [mvisonneau/gitlab-ci-pipelines-exporter#219]
I am getting error when trying to see pod logs and metrics are not coming
Note: have added all projects and using wild card, would you 

```
# projects:
  #   - name: foo/project
  #   - name: bar/project
  # wildcards:
  #   - owner:
  #       name: foo
  #       kind: group
```

Error:
{"error":"json: cannot unmarshal array into Go value of type gitlab.Project","level":"warning","msg":"pulling refs from project","project-name":"","time":"2021-01-22T02:49:01Z"}

**Comment by mvisonneau** [comment]
👋 hey @udaymadu, could you please share a sanitized version of your config file?

**Comment by udaymadu** [comment]
[values.zip](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/files/5922941/values.zip)

**Comment by udaymadu** [comment]
I am getting below error now
kubectl logs gitlab-ci-pipelines-gitlab-ci-pipelines-exporter-767bb9c6d7gh8l
{"level":"error","msg":"unable to parse config file: yaml: unmarshal errors:\n  line 5: cannot unmarshal !!seq into schemas.Project\n  line 7: cannot unmarshal !!seq into schemas.Wildcard","time":"2021-02-04T03:14:30Z"}

**Comment by mvisonneau** [comment]
@udaymadu, I believe the issue you are seeing is unrelated to this one, your config file contains invalid syntax. I think what you are looking for is something like:

```yaml
wildcards: [{}]
```

**Comment by mvisonneau** [comment]
will close this issue, feel free to reopen if necessary!
