### ISSUE TITLE
fetch all doesn't work as in documentation

### ISSUE THREAD

**Issue by szemkhel** [mvisonneau/gitlab-ci-pipelines-exporter#22]
if I understand documentation well I should be able to configure fetch all with this config:
> wildcards:
>  - refs: ".*"

But I'm getting:
> "0 project(s) configured"
> "Listing all projects using search pattern : '' with owner '' ()"
> "Invalid owner kind '' must be either 'user' or 'group'"
> "exporter started!"

I guess from other issues that 'fetch all' is a no go feature, for now, so I would suggest changes in documentation - so it doesn't give an impression it is possible.

**Comment by mvisonneau** [comment]
@szemkhel, this feature is supported since `0.2.8`. Which version are you using ?

**Comment by mvisonneau** [comment]
Feel free to reopen if this is still happening with versions `>= 0.2.8`
