### ISSUE TITLE
Possibility of the exporter to scrape the last run pipeline only

### ISSUE THREAD

**Issue by benjie91** [mvisonneau/gitlab-ci-pipelines-exporter#228]
More of a question or if not a feature request.

Is it possible for the exporter to scrape the last pipeline run only?

When I was using regexp, it is scraping all my tags and this is not really useful in the dashboard.

**Comment by mvisonneau** [comment]
👋 hey @benjie91, which regexp have you been using? The default one is: `^main|master$` which suposely fetches only the latest pipeline of the default branch

**Comment by benjie91** [comment]
I was fetching my tag as well
^(master)|(v?\d+\.\d+\.\d+)$

Essentially, it is retrieving tags such as v1.0.0 , 2.0.0 as well

**Comment by benjie91** [comment]
My bad... closing this issue
