### ISSUE TITLE
dashboard issue

### ISSUE THREAD

**Issue by szemkhel** [mvisonneau/gitlab-ci-pipelines-exporter#23]
I couldn't find any source code for dashboard, so I'll report issue here.
I have applied this change locally in my JSON and my dashboard started working properly. As by default it wasn't.
all occurrences of gitlab_ci_pipeline_status suppose to be changed to gitlab_ci_pipeline_last_run_status in this file: https://grafana.com/grafana/dashboards/10620

**Comment by mvisonneau** [comment]
Example dashboard is stored here : https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/example/grafana/dashboard.json

**Comment by szemkhel** [comment]
yes, thank you I have fixed version, I'm more concerned that people like me who get here to this project by searching graph in graphana webpage - already have the one from their page, so maybe it should be updated there?

**Comment by mvisonneau** [comment]
I have updated the dashboard quite recently 👍 going to close this one for now.
