### ISSUE TITLE
Not able to fetch any job information

### ISSUE THREAD

**Issue by javigarciafort** [mvisonneau/gitlab-ci-pipelines-exporter#236]
Hi,

We're trying to fetch jobs informations to watch it in the Grafana "GitLab CI jobs" dashboard but we're not able to make it work. We're using exporter v0.4.7 and GitLab v12.7.5 versions. This is our configuration for the exporter: 

![config yml](https://user-images.githubusercontent.com/74608016/108698452-6fbe6600-7504-11eb-8319-8d32b9dd2e2d.jpg)

In exporter logs we're seeing the following errors when we enable the pipeline:jobs configuration: 

time="2021-02-22T10:17:49Z" level=warning msg="pulling ref metrics" error="GET https://XXXX/api/v4/projects/XXXX/XXXX/XXXX/pipelines/34709/bridges: 404 failed to parse unknown error format" project-name=XXXX/XXXX/XXXX ref=hotfix/XXXX

Any help would be appreciated!

**Comment by mvisonneau** [comment]
👋 hey @javigarciafort,

At first sight it looks like the error occurs onto a pipeline bridge request. Does it cause the exporter to crash or do you simply end up with no metrics for particular projects ? 🤔

I am concerned that their API spec around pipeline triggers/bridges may have changed substancially since `v12.7.5` 😞

**Comment by javigarciafort** [comment]
Hi @mvisonneau,

Thanks for your quick reply. 

The exporter doesn't crash, in fact we're able to fetch pipelines and environment metrics, but we can't fetch any job metrics. 

Regards.

**Comment by javigarciafort** [comment]
Hi again @mvisonneau, 

Just to add some extra information, in the exporter logs, we can see that it's getting some job information from environments:

_gitlab_ci_environment_deployment_job_id{environment="desarrollo",project="XXXX/XXXX/XXXX"} 108109_

But there's no other job metrics apart from those.

**Comment by javigarciafort** [comment]
Finally, we could fix it disabling jobs from child pipelines:

![gitlab-ci-exporter-config](https://user-images.githubusercontent.com/74608016/108732572-fcc9e500-752d-11eb-943e-a1b9f072408e.jpg)

It seems that before GitLab 13.3, requests for child pipelines returns a 404 error: 

https://docs.gitlab.com/ee/api/pipelines.html

In our scenario, we don't use child pipelines, so we could workaround this error disabling jobs from child pipelines.

**Comment by mvisonneau** [comment]
👋 @javigarciafort, thanks for the followup on this issue. I reckon I will need to start some exporter/gitlab versioning compatibility matrix!
