### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by g0tbread** [mvisonneau/gitlab-ci-pipelines-exporter#238]
Hi， @mvisonneau
During the deployment, I found that the health check prompt 503 error，Here is my config info:
egrep -v '(^#|^$|#)' values.yaml
...
service:
  type: ClusterIP
  port: 80
  labels: {}
  annotations: {}

**livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  periodSeconds: 30**
...
args:
  - --config
  - /etc/config.yml
  - --log-format
  - json
...

# cat Chart.yaml 
apiVersion: v1
name: gitlab-ci-pipelines-exporter
version: 0.1.2
appVersion: v0.4.8

**Comment by g0tbread** [comment]
ignore it

**Comment by dominik-bln** [comment]
We are seeing the same 503 when deploying the service via Helm, the metrics page is working though. What did you do to solve the issue?

**Comment by dominik-bln** [comment]
Figured it out: We are running a self-hosted Gitlab instance and the checking the health of that server didn't work, you either need to configure the correct health endpoint of your Gitlab instance via `health_url: https://gitlab.example.com/-/health`or set `enable_health_check: false`
