### ISSUE TITLE
Readiness probe fails with error code 503

### ISSUE THREAD

**Issue by YYashwanth** [mvisonneau/gitlab-ci-pipelines-exporter#249]
Hello,

I have deployed the tool using helm and I see that the redis pod runs normal but the exporter pod is throwing the following error:

> Readiness probe failed: Get http://:8080/health/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Readiness probe failed: HTTP probe failed with statuscode: 503

this is the output of netstat -n from within the container
> /bin $ netstat -n
> Active Internet connections (w/o servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:58850 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:58944 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:59134 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:59192 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:59042 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:59258 TIME_WAIT   
> tcp        0      0 ::ffff:10.226.43.15:8080 ::ffff:10.226.42.132:58894 TIME_WAIT   
> Active UNIX domain sockets (w/o servers)
> Proto RefCnt Flags       Type       State         I-Node Path

> /bin $ netstat
> Active Internet connections (w/o servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:58850 TIME_WAIT   
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:58944 TIME_WAIT   
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:59134 TIME_WAIT   
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:59192 TIME_WAIT   
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:59042 TIME_WAIT   
> tcp        0      0 gitlab-ci-pipelines-exporter-64c7f4d7bf-6kbz9:8080 10-226-42-132.kubecost-prometheus-node-exporter.kubecost.svc.cluster.local:58894 TIME_WAIT

This is what I find in the logs of the exporter pod

> {"level":"info","listen-address":":8080","metrics-endpoint-enabled":true,"msg":"http server started","openmetrics-encoding-enabled":false,"pprof-endpoint-enabled":false,"time":"2021-04-08T05:24:57Z","webhook-endpoint-enabled":false}

> {"level":"warning","msg":"taskqtask=\"getProjectsFromWildcardTask\" failed (will retry=1 in dur=30s): unable to list projects with search pattern '' from the GitLab API : Get \"https://gitlab.example.com/api/v4/groups/mnf-group/projects?archived=false\u0026include_subgroups=false\u0026page=1\u0026per_page=100\u0026search=\u0026with_shared=false\": dial tcp: lookup gitlab.example.com on 172.20.0.10:53: no such host","time":"2021-04-08T05:24:58Z"}

I am trying to lookup the projects within a group inside our gitlab account. wrt the second error, how do I configure the tool to get the projects/repos from the mnf-group within gitlab? I have provided an access token too.

I am running EKS 1.15. Please let me know if you need any more information in guiding me to solve this.

@mvisonneau

**Comment by mvisonneau** [comment]
:wave: hey @YYashwanth,

Could you please share a sanitized version of your configuration file?

Also, can you confirm that are able to resolve records from your DNS server correctly : `dial tcp: lookup gitlab.example.com on 172.20.0.10:53: no such host`?

**Comment by YYashwanth** [comment]
Sorry @mvisonneau. It was my fault. I did not edit the config.yml properly and actually left the url as gitlab.example.com. This was the reason everything was failing. Sorry for the trouble.
