### ISSUE TITLE
Label name "username" missing in label map

### ISSUE THREAD

**Issue by kkmiquido** [mvisonneau/gitlab-ci-pipelines-exporter#266]
Hello, 

after upgrading gitlab-ci-pipelines-exporter from version v0.4.7 to v0.4.8 I'm getting following error when starting it:

> 2021/05/06 09:51:04 http: panic serving 172.17.0.1:46414: label name "username" missing in label map
goroutine 155 [running]:
net/http.(*conn).serve.func1(0xc00012a8c0)
	net/http/server.go:1824 +0x153
panic(0xb35ba0, 0xc0002088b0)
	runtime/panic.go:971 +0x499
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc00000e1a0, 0xc0003b9ec0, 0x7f7a00000009, 0xc0000ba518)
	github.com/prometheus/client_golang@v1.9.0/prometheus/gauge.go:228 +0xe5
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.(*Registry).ExportMetrics(0xc000208b60, 0x0, 0x0)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/metrics.go:101 +0x287
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.MetricsHandler(0xcff9c0, 0xc0001380e0, 0xc0001d6100)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/metrics.go:73 +0x45
net/http.HandlerFunc.ServeHTTP(0xc57ef8, 0xcff9c0, 0xc0001380e0, 0xc0001d6100)
	net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00007f040, 0xcff9c0, 0xc0001380e0, 0xc0001d6100)
	net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000138000, 0xcff9c0, 0xc0001380e0, 0xc0001d6100)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00012a8c0, 0xd00ed8, 0xc0001b4400)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

I'm assuming that I need to add something to configuration but I can't find any reference to `username` property in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md

Would appreciate any help here :)

Thanks

**Comment by mvisonneau** [comment]
:wave: hey @kkmiquido, are you using it with a Redis backend? :thinking:

**Comment by kkmiquido** [comment]
@mvisonneau yes, I have following redis configuration in yml file:

```
redis:
  url: redis://redis:6379
```

**Comment by mvisonneau** [comment]
ok thanks for the confirmation :+1:

Unfortunately the only short-term option I can think of would be to delete the `metrics` key in redis and :recycle: the gitlab-ci-pipelines-exporter process :(
