### ISSUE TITLE
Add pipeline queued duration metric

### ISSUE THREAD

**Issue by linux-wizard** [mvisonneau/gitlab-ci-pipelines-exporter#272]
Presently we are exposing following metrics for a pipeline:
- `gitlab_ci_pipeline_timestamp`: Timestamp of the last update of the most recent pipeline (should be updated_at field)
- `gitlab_ci_pipeline_status`: pipeline status (should be status field)
- `gitlab_ci_pipeline_run_count`: I guess this one is calculated internally
- `gitlab_ci_pipeline_id`: Pipeline ID (should id field)
- `gitlab_ci_pipeline_duration_seconds`: Duration in seconds of the most recent pipeline (should come I guess from duration field.

Is it possible to add support for `gitlab_ci_pipeline_queued_duration_seconds` = the duration a pipeline has been queued (in pending state) ? 
This can be calculated I think using `started_at` - `updated_at`.

In GitLab 13.12, it seems this will be exposed as `queued_duration` field, and this will be calculated as `started_at - created_at`: https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/models/ci/pipeline.rb#L851

**Comment by mvisonneau** [comment]
thanks again for this contribution, closing this as it has been merged as part of #273

**Comment by mvisonneau** [comment]
released as part of [v0.5.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.5.0)!
