### ISSUE TITLE
Add jobs queued duration metric

### ISSUE THREAD

**Issue by linux-wizard** [mvisonneau/gitlab-ci-pipelines-exporter#274]
Presently we are exposing following metrics for a job:

- `gitlab_ci_pipeline_job_timestamp`: Timestamp of the last update of the most recent job (should be updated_at field)
- `gitlab_ci_pipeline_job_status`: job status (should be status field)
- `gitlab_ci_pipeline_job_run_count`: I guess this one is calculated internally
- `gitlab_ci_pipeline_job_id`: Job ID (should id field)
- `gitlab_ci_pipeline_job_duration_seconds`: Duration in seconds of the most recent job
- `gitlab_ci_pipeline_job_artifact_size_bytes`: Artifact size in bytes (sum of all of them) of the most recent job

Is it possible to add support for `gitlab_ci_pipeline_job_queued_duration_seconds` = the duration a job has been queued (in pending state) ?
This can be calculated I think using `started_at - updated_at`.

In GitLab 13.12, it seems this will be exposed as queued_duration field: 
https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/graphql/types/ci/job_type.rb#L47
https://docs.gitlab.com/ee/api/jobs.html

**Comment by mvisonneau** [comment]
released as part of [v0.5.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.5.0)!
