### ISSUE TITLE
Webhook push principle without pulling all accessible projects from wildcard after first webhook received

### ISSUE THREAD

**Issue by gvizdpeter** [mvisonneau/gitlab-ci-pipelines-exporter#281]
Hello I am using this configuration:

```
wildcards:
  - {}

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

server:
  webhook:
    enabled: true

```

and I have problem that after first received webhook all projects (according to wildcard) are pulled. Is here some configuration option, how to avoid this behaviour? Because I want to have webhoook available for all users of our gitlab instance, so they will be able to simply add webhook and work with scraped data, but I want data only for projects that have this webhook configured.

**Comment by mvisonneau** [comment]
:wave: hey @gvizdpeter, thank you for raising this issue.

If you use such a configuration, the logic will indeed run a listing of all of the available projects on the first request. It will not trigger it on subsequent queries though as the project will likely have been discovered then.

The alternatives I can think of at the moment would be to leverage more precise wildcards such as:

```
wildcards:
  - owner: { name: foo, kind: group, include_subgroups: true }
  - owner: { name: bar, kind: group, include_subgroups: true }
```

This will reduce the number of projects being listed on the first attempt.

You can also leverage Redis in order to cache your data and avoid this behaviour whenever you restart the exporter.

Hope this helps!

**Comment by gvizdpeter** [comment]
Hello @mvisonneau, thank you for quick response, yes I was wondering wether there is some configuration option to minimize amount of data in prometheus, but according to your response I will have to do it on prometheus side.

**Comment by mvisonneau** [comment]
Maybe give a try to `max_age_seconds` parameters to only keep most recently updated pipelines and therefore reduce the number of metrics being exported otherwise :thinking:

**Comment by gvizdpeter** [comment]
I was wondering about filter by topics field, but I found another problem. When I have configuration like this
```
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: true
    interval_seconds: 30

  environments_from_projects:
    on_init: false
    scheduled: true
    interval_seconds: 30

  refs_from_projects:
    on_init: false
    scheduled: true
    interval_seconds: 30

  metrics:
    on_init: false
    scheduled: true
    interval_seconds: 30

wildcards:
  -
    owner:
      name: GVIZDP01

server:
  webhook:
    enabled: true
```

everything is fine and I get metrics like this:
`gitlab_ci_pipeline_id{kind="branch",project="GVIZDP01/gitlab-tf-test",ref="master",topics="gitlab-ci-pipeline-exporter-aware,scheduled-job",variables=""} 36467`

but when I have configuration like this:
```
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

wildcards:
  -
    owner:
      name: GVIZDP01

server:
  webhook:
    enabled: true
```
I get metrics without topics:
`gitlab_ci_pipeline_id{kind="branch",project="GVIZDP01/gitlab-tf-test",ref="master",topics="",variables=""} 36467`

Is there some config option how can I get topics from webook?

**Comment by mvisonneau** [comment]
interesting, looks like a bug, I logged a new issue to look it up : #282

**Comment by gvizdpeter** [comment]
Thank you @mvisonneau , I will follow this issue.

**Comment by Pigueiras** [comment]
Hello @mvisonneau, I was trying to use webhooks to not being hit by the queue buffer exhausted as you recommended in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/327

If I try to disable all pulling with:

```
log:
   level: debug

gitlab:
  url: <>
  # You can also configure the token using --gitlab-token
  # or the $GCPE_GITLAB_TOKEN environment variable
  token: <>
server:
  webhook:
    enabled: true
    secret_token: <>
project_defaults:
  pull:
    refs:
      tags:
        enabled: false
      branches:
        enabled: true
        regexp: ".*"
        most_recent: 5

wildcards:
  - {}

garbage_collect:
  projects:
    on_init: false
    scheduled: false
  environments:
    on_init: false
    scheduled: false
  refs:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
  environments_from_projects:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
```

But it doesn't trigger metrics when it receives the webhook, because it's being handled by the initial pull:

```
DEBU[2023-01-13T09:58:52+01:00] webhook request                               ip-address="1.2.3.4:42566" user-agent=GitLab/15.6.4-ee
INFO[2023-01-13T09:58:52+01:00] project ref not currently exported but its configuration matches a wildcard, triggering a pull of the projects from this wildcard  project-name=test-projects/test ref=test ref-kind=branch
INFO[2023-01-13T09:58:52+01:00] done looking up for wildcards matching the project ref  project-name=test-projects/test ref=test ref-kind=branch
DEBU[2023-01-13T09:58:52+01:00] listing all projects from wildcard            wildcard-archived=false wildcard-owner-include-subgroups=false wildcard-owner-kind= wildcard-owner-name= wildcard-search=
DEBU[2023-01-13T09:58:54+01:00] webhook request                               ip-address="1.2.3.4:42570" user-agent=GitLab/15.6.4-ee
DEBU[2023-01-13T09:58:54+01:00] task already queued, skipping scheduling of task..  task_type=PullProjectsFromWildcard task_unique_id=0
INFO[2023-01-13T09:58:54+01:00] project ref not currently exported but its configuration matches a wildcard, triggering a pull of the projects from this wildcard  project-name=test-projects/test ref=test ref-kind=branch
INFO[2023-01-13T09:58:54+01:00] done looking up for wildcards matching the project ref  project-name=test-projects/test ref=test ref-kind=branch
DEBU[2023-01-13T09:59:00+01:00] jobs/pipelines not enabled on project, skipping  project-id=2031 project-name=conn/personal/isbister/blueetl_ji_analyses wildcard-archived=false wildcard-owner-include-subgroups=false wildcard-owner-kind= wildcard-owner-name= wildcard-search=
DEBU[2023-01-13T09:59:07+01:00] webhook request                               ip-address="1.2.3.4:48082" user-agent=GitLab/15.6.4-ee
DEBU[2023-01-13T09:59:07+01:00] task already queued, skipping scheduling of task..  task_type=PullProjectsFromWildcard task_unique_id=0
INFO[2023-01-13T09:59:07+01:00] project ref not currently exported but its configuration matches a wildcard, triggering a pull of the projects from this wildcard  project-name=test-projects/test ref=test ref-kind=branch
INFO[2023-01-13T09:59:07+01:00] done looking up for wildcards matching the project ref  project-name=test-projects/test ref=test ref-kind=branch
```

But since there are a lot of projects I am trying to get metrics from, I'm being hit by a lot of (and the project that trigger the webhook is skipped):

```
WARN[2023-01-13T09:59:38+01:00] queue buffer size exhausted, skipping scheduling of task..  task_type=PullEnvironmentsFromProject task_unique_id=2773831717
```

If I enable redis (with the same previous config):

```
DEBU[2023-01-13T10:02:54+01:00] webhook request                               ip-address="1.2.3.4:34176" user-agent=GitLab/15.6.4-ee
ERRO[2023-01-13T10:02:54+01:00] reading ref from the store                    error="context canceled" project-name=test-projects/test ref=test ref-kind=branch
DEBU[2023-01-13T10:02:54+01:00] webhook request                               ip-address="1.2.3.4:34184" user-agent=GitLab/15.6.4-ee
ERRO[2023-01-13T10:02:54+01:00] reading ref from the store                    error="context canceled" project-name=test-projects/test ref=test ref-kind=branch
```

Which probably means that if I put all the `on_init` and `scheduled` with `false`, redis doesn't get filled with information and it simply fails to find any information about the project that trigger the

I enable the `on_init` pulls, I hit again the same problem of the queue buffer exhausted. And if the project with the webhook is not in the list I get the exact same error as before.

So is there any way to avoid the initial pull so the exporter only relies on the push model and only updates the information depending on the webhooks it receives?
