### ISSUE TITLE
Documentation: Metrics endpoint for Kubernetes deployments

### ISSUE THREAD

**Issue by sethatron** [mvisonneau/gitlab-ci-pipelines-exporter#284]
Hello, so far this service seems like it has a lot of potential; however, there is one thing that I'm having trouble figuring out: where are the actual metrics exposed in a kubernetes deployment? I've checked the Pod logs to verify the pipeline metrics can be called, which appears to be the case:

```
time="2021-06-09T14:40:54Z" level=info msg="exporter configured" gitlab-endpoint="https://gitlab.com" pull-projects-from-wildcards-interval=1800s pull-projects-refs-from-projects-interval=300s pull-projects-refs-metrics-interval=30s pull-rate-limit=10rps
time="2021-06-09T14:40:54Z" level=info msg="scheduling projects from wildcards pull" wildcards-count=0
time="2021-06-09T14:40:54Z" level=info msg="scheduling projects refs from projects pull" projects-count=1
time="2021-06-09T14:40:54Z" level=info msg="scheduling metrics pull" project-refs-count=0
time="2021-06-09T14:40:54Z" level=info msg="http server started" listen-address=":8080" metrics-endpoint-enabled=true pprof-endpoint-enabled=false webhook-endpoint-enabled=false
time="2021-06-09T14:40:55Z" level=info msg="discovered new project ref" project-id=19279108 project-name=abacusinsights/refimpl/debian-patching-refimpl project-ref=master project-ref-kind=branch
time="2021-06-09T14:41:24Z" level=info msg="scheduling metrics pull" project-refs-count=1
time="2021-06-09T14:41:54Z" level=info msg="scheduling metrics pull" project-refs-count=1
```

However, the `--raw /metrics` endpoint doesn't contain any gcpe/gitlab/pipeline metrics. I was hoping that the/a Pod would produce the Logs so I can use CloudWatch agent to automatically pull the Logs from a Pod into my AWS CloudWatch Log Group. I'm not very familiar with exposing services in K8s, but it seems they are maybe being pushed over the (Pod's) local http server on 8080? I've tried to `port-forward -n gitlab-metrics gitlab-ci-pipelines-exporter-97b849c9b-rfgrt 8080:8080` to verify this theory, but I'm getting `404 page not found`. 

The real ask here is if you could update the documentation to include instructions for doing this in Kubernetes, but I would also be very appreciative if you could quickly explain here for me :)

Thank you very much

**Comment by sethatron** [comment]
Just wanted to add further context here as I've figured out I was making a silly mistake. I do see the metrics in the Pod's 8080 /metrics endpoint, it just appears that I'll need to configure the Pod annotations for Prometheus (example: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L106)

**Comment by mvisonneau** [comment]
👋 hey @sethatron, glad you figured your issue out! I will close it then! 🙇
