### ISSUE TITLE
Memory used continues to grow

### ISSUE THREAD

**Issue by wenzhao43** [mvisonneau/gitlab-ci-pipelines-exporter#294]
hi~ I found that after the service started，the memory used of gitlab-ci-exporter  continued to grow. When the memory used reaches half of the limit memory the container will crash. My image tag is v0.5.0.
Is there any solution?
![image](https://user-images.githubusercontent.com/65001757/125032890-2e001780-e0c1-11eb-82a2-fca00c2fb89e.png)

**Comment by mvisonneau** [comment]
thanks for reporting this @wenzhao43, looks like a nice memory leak at first sight. I will look into it. Do you have the logs of when the container crashes though?

**Comment by mvisonneau** [comment]
indeed, it seems that the scheduler is creating way more goroutines than it should

![image](https://user-images.githubusercontent.com/1761583/125087682-96042d00-e0c4-11eb-8186-0af1c8fed9e5.png)

**Comment by cwandrey** [comment]
Hello, 
thanks for the fix. 
The container runs a lot more stable with it.

**Comment by mvisonneau** [comment]
The fix is part of `v0.5.1`, I will close this issue as it seems to be sorted :+1:
