### ISSUE TITLE
Latest docker image appears broken

### ISSUE THREAD

**Issue by donaldrich80** [mvisonneau/gitlab-ci-pipelines-exporter#298]
I believe there were faults introduced into the latest docker tag 

Issue #1

 - The image wouldn't start successfully until I explicitly added the run command

Issue #2

Even after adding the run command, there appears to be an issue with the image running, the culprit appears to be...

```
time="2021-07-17T10:08:21Z" level=fatal error="listen unix ./.gcpe-monitor.sock: bind: permission denied"
```

Reverting to the previous version tag is a viable workaround.

Thanks for the awesome image BTW!

**Comment by mvisonneau** [comment]
Thank you for raising this @donaldrich80, indeed this is part of some recent changes which were yet to be released :) I added further documentation regarding it and reverted part of the breaking changes https://github.com/mvisonneau/gitlab-ci-pipelines-exporter#monitor--troubleshoot

Please note that the latest tags are based upon the `main` branch though and should not considered to be stable!

**Comment by schoentoon** [comment]
I'm getting a similar error with the latest docker image (and `v0.5.1`) even after adding the `run` command.

```
time="2021-07-19T17:39:37Z" level=fatal error="listen: unknown network "
```

Not sure if related though, reverted back to v0.5.0 for now.

**Comment by mvisonneau** [comment]
indeed my bad @schoentoon :facepalm:, it should be fixed following  519f8b2 :bow:

**Comment by OPSTime** [comment]
**version： 5.1
There still seems to be a issue：**

DEBU[2021-08-07T12:21:10+08:00] task scheduled                                interval_seconds=1800 task=PullProjectsFromWildcards
INFO[2021-08-07T12:21:10+08:00] internal monitoring listener set              host= scheme=
INFO[2021-08-07T12:21:10+08:00] scheduling refs from projects pull            projects-count=10
FATA[2021-08-07T12:21:10+08:00]                                               error="listen: unknown network "

**Comment by mvisonneau** [comment]
@OPSTime this fix hasn't been released yet, you can leverage it as part of the `latest` tag

**Comment by OPSTime** [comment]
Please look at this issues @mvisonneau ：
https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/258
