### ISSUE TITLE
Separate monitoring for subchart in project

### ISSUE THREAD

**Issue by Sakojpa** [mvisonneau/gitlab-ci-pipelines-exporter#30]
Hi! 
It's be a good idea to monitor subchart in project like separete projects.  My project user/foo counts 70 charts bar1 bar2 bar3 and etc, but triggering bar1 enable monitoring for all project user/foo.
It would be better if trigger user/foo/bar1 will have separete monitoring from user/foo/bar2

**Comment by mvisonneau** [comment]
👋 hey @Sakojpa, I am not sure to understand your request. What is a subchart/chart?

**Comment by Sakojpa** [comment]
Oh, it's my fault :) of couse not chart, but dirs in projects. I use projects like a vault for my charts. So structure like this
User
-------foo
------------- bar1
------------- bar2
------------- bar3

**Comment by mvisonneau** [comment]
do you actually have different pipelines for those folders within your project ? 🤔

**Comment by Sakojpa** [comment]
Hm, pipeline is the same, but it's triggered with different variables. Think it can't be handle with your repo :(
