### ISSUE TITLE
Gitlab_ci_pipeline_status with Environment

### ISSUE THREAD

**Issue by luizgmgomes** [mvisonneau/gitlab-ci-pipelines-exporter#303]
Hello!👋  First of all, thank you very much for this great project, it's been very helpful for me and many others! @mvisonneau! 

We are looking to be able to filter for project name, branch (ref), status and environment on the same metric. This will help to create a dashboard of pipelines' running state linking its project, branch and environment.

Unfortunately using only "gitlab_ci_pipeline_status" and trying to reach for [variables](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/metrics.md#variables), gitlab doesn't seem to return variables configured through [.gitlab-ci.yml](https://docs.gitlab.com/ee/ci/variables/#create-a-custom-cicd-variable-in-the-gitlab-ciyml-file).

In my case only adding "environment" to "gitlab_ci_pipeline_status" would solve this matter.

Thanks a lot!

**Comment by mvisonneau** [comment]
hey @luizgmgomes, thank you for the kind feedback.

Indeed, as of today, the variables returned by the GitLab API are only the ones manually defined.

As for the environment information, I am not sure how that could work at this level as they can be associated with a job. A pipelines can hold multiple environments start/stop definitions 🤔

**Comment by luizgmgomes** [comment]
Thanks, @mvisonneau! Looks like this is the problem, where those pipelines needs to be run manually to return a variable from [.gitlab-ci.yml](https://docs.gitlab.com/ee/ci/variables/#create-a-custom-cicd-variable-in-the-gitlab-ciyml-file). I guess we will have to find a different way to implement or just run them manually once GitlabCI has this impeditive.

Thanks again for your help and this brilliant project!
