### ISSUE TITLE
End point not connected / 401 failed to parse unknown error format / readiness & liveness probe failing

### ISSUE THREAD

**Issue by NagabhushanaYR** [mvisonneau/gitlab-ci-pipelines-exporter#313]
Hi ,
I have installed gitlab-ci-pipelines-exporter in EKS cluster and seems some connection issues to my gitlab api.
Pod logs:
{"error":"GET https://XXXX.com/api/v4/projects/projectID/repository/branches: 401 failed to parse unknown error format","level":"warning","msg":"pulling refs from project","project-name":"projectID","time":"2021-08-17T08:53:36Z"}
{"environments-count":0,"level":"info","msg":"scheduling metrics pull","refs-count":0,"time":"2021-08-17T08:53:36Z"}

Readiness probe failed: Get "http://XXX.XXX.XXX.XX:8080/health/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Liveness probe failed: Get "http://XXX.XXX.XXX.XX:8080/health/live": dial tcp XXX.XXX.XXX.XX:8080: connect: connection refused 

Values.yaml
   gitlab:
     url: https://xxxx.com/
     token: xxxxxxxxx
   projects:
     - name: projectID
  
When I try to access the URL from postman by passing the token,  I am able to access the project.   I am not sure if access token is not actually referenced to access the API Or if any permissions at project level / group level need set to access the Gitlab API URL

**Comment by NagabhushanaYR** [comment]
Changing the issue description.

My earlier posted issue regarding API giving 401 error is resolved after passing token in the gitlab URL.   But I am not able to view gitlab metrics in the prometheus.   

![image](https://user-images.githubusercontent.com/77423814/129921419-f931b464-fbf0-4212-852a-75e0689529ce.png)

Below are the metrics I see when I query metrics endpoint
![image](https://user-images.githubusercontent.com/77423814/129921659-1e2f4e76-cb6e-4fad-89b3-fb1aa32b8096.png)

am I missing any other configuration or permissions ?

**Comment by mvisonneau** [comment]
:wave: hey @NagabhushanaYR, are you sure your token is valid / configured correctly? At first sight, according to the 401 you are getting it looks like some permission issues with the GitLab API.

Which version of GitLab are you using?

**Comment by NagabhushanaYR** [comment]
Hi ,  gitlab version:  GitLab Community Edition 14.1.2

I was getting 401 error initially and when I try to pass access token through URL in values.yaml as below, everything seems to be started working but ended up in issues while seeing the metrics.

New gitlab url:  https://access_token=xxxxxxx@XXXX.com

I am owner of the project and have given all access permission to my personal token for gitlab API

**Comment by NagabhushanaYR** [comment]
I am able to figure out the issue.  My AKS cluster has access restrictions to connect to github API url.   I have fixed the issue and now able to see some metrics in prometheus & grafana. 

Thanks for your inputs.
