### ISSUE TITLE
grafana shows outdated data, what is the reason?

### ISSUE THREAD

**Issue by ProGesss** [mvisonneau/gitlab-ci-pipelines-exporter#324]
why grafana shows outdated data, what is the reason?

![Opera Snapshot_2021-09-06_164831_mvl powowai com](https://user-images.githubusercontent.com/49198739/132227102-c09be603-ff78-4ebc-9ab3-5d2114453de3.png)
![Opera Snapshot_2021-09-06_164820_mvl powowai com](https://user-images.githubusercontent.com/49198739/132227114-2a7eea65-9c9a-426f-8fc6-d99b155ede1e.png)
![Opera Snapshot_2021-09-06_164749_mvl powowai com](https://user-images.githubusercontent.com/49198739/132227118-6bb3bc53-6f48-4100-8817-4ccc098f889d.png)

Config gitlab-ci-pipelines-exporter: 

log:
  level: info
  format: text

gitlab:
  url: https://gitlab.com

  token: "my_token"

wildcards:
  - owner: { name: foo, kind: group, include_subgroups: true }

wildcards:
  - {}

**Comment by mvisonneau** [comment]
:wave: hey @ProGesss, at first sight, I would assume this is work as design, you can have a look at the [configuration syntax here](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter)/blob/main/docs/configuration_syntax.md). If you want the exporter to omit refs older than a specific duration, you can leverage the `max_age_seconds` parameter.

**Comment by ProGesss** [comment]
>  hey @ProGesss, at first sight, I would assume this is work as design, you can have a look at the [configuration syntax here](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter)/blob/main/docs/configuration_syntax.md). If you want the exporter to omit refs older than a specific duration, you can leverage the `max_age_seconds` parameter.


hello, thanks, I tried it, but grafana still shows outdated indicators, what else can it be connected with?
