### ISSUE TITLE
can't find yml file on docker start

### ISSUE THREAD

**Issue by thespamer** [mvisonneau/gitlab-ci-pipelines-exporter#330]
➜  gitlab-ci-pipelines-exporter git:(main) docker run -it --rm \
   --name gitlab-ci-pipelines-exporter \
   -v $(pwd)/config.yml:/etc/config.yml \
   -p 8080:8080 \
   mvisonneau/gitlab-ci-pipelines-exporter:latest \
run
ERRO[0000] open gitlab-ci-pipelines-exporter.yml: no such file or directory

But i have it on root path;

➜  gitlab-ci-pipelines-exporter git:(main) ls -l
total 53384
-rw-r--r--  1 juliano  staff     25035 22 Set 07:49 CHANGELOG.md
-rw-r--r--  1 juliano  staff       398 22 Set 07:49 Dockerfile
-rw-r--r--  1 juliano  staff     10766 22 Set 07:49 LICENSE
-rw-r--r--  1 juliano  staff      3520 22 Set 07:49 Makefile
-rw-r--r--  1 juliano  staff     18124 22 Set 07:49 README.md
drwxr-xr-x  3 juliano  staff        96 22 Set 07:49 cmd
drwxr-xr-x  2 juliano  staff        64 22 Set 08:23 config.yml
drwxr-xr-x  5 juliano  staff       160 22 Set 07:49 docs
drwxr-xr-x  5 juliano  staff       160 22 Set 07:49 examples
-rwxr-xr-x  1 juliano  staff  27178336 22 Set 08:20 gitlab-ci-pipelines-exporter
-rw-r--r--  1 juliano  staff       569 22 Set 07:49 gitlab-ci-pipelines-exporter.yml
-rw-r--r--  1 juliano  staff      3977 22 Set 07:49 go.mod
-rw-r--r--  1 juliano  staff     71162 22 Set 07:49 go.sum
drwxr-xr-x  4 juliano  staff       128 22 Set 07:49 internal
drwxr-xr-x  9 juliano  staff       288 22 Set 07:49 pkg

any clue?!

**Comment by mvisonneau** [comment]
:wave: hey @thespamer, the default location the binary is looking into for the config file is `./gitlab-ci-pipelines-exporter.yml`. (https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/internal/cli/cli.go#L49)

Within the container image, the workdir being `/` it is therefore `/gitlab-ci-pipelines-exporter.yml`. You can override this value by setting the `GCPE_CONFIG=/etc/config.yml` env variable.
