### ISSUE TITLE
Helm chart: Pipelines exported not scraped by Prometheus

### ISSUE THREAD

**Issue by cedricve** [mvisonneau/gitlab-ci-pipelines-exporter#331]
Hello, I'm trying to spin up the exporter in my Kubernetes cluster using the Helm chart. I've made the deployment, and can see the gitlab exporter is providing metrics on `:8080/metrics`. What I noticed is that on the prometheus dashboard (installed with the Prometheus operator), is not discovering the metrics  `:8080/metrics` endpoint. I can confirm the Prometheus  installation can find my other exporters such as Kafka.

<img width="1386" alt="Screenshot 2021-09-23 at 11 20 26" src="https://user-images.githubusercontent.com/1546779/134483135-f0f6120d-c2f6-4685-a2ac-988449793158.png">

To confirm if I'm having the correct configuration, I spinned up the docker example, and I can confirm that the pipelines are showing correctly. Any ideas what is different with the helm chart?

**Comment by mvisonneau** [comment]
👋 hey @cedricve, as you are using the Prometheus operator, have you configured a `ServiceMonitor` resource? The helm chart has a feature flag to do it automatically but is off by default: https://github.com/mvisonneau/helm-charts/blob/main/charts/gitlab-ci-pipelines-exporter/values.yaml#L135-L139

**Comment by cedricve** [comment]
boom ;) this is for the kerberos.io project btw.

<img width="1332" alt="Screenshot 2021-09-23 at 17 20 59" src="https://user-images.githubusercontent.com/1546779/134536350-328fff5f-89ec-4b6b-8b50-30c8fd63e85f.png">
