### ISSUE TITLE
Filter projects by tags

### ISSUE THREAD

**Issue by Cobra1978** [mvisonneau/gitlab-ci-pipelines-exporter#35]
Hi.

For us well be very useful to filter projects by tag, because we want to track with this dasboard only some types of project.

Unfortunately project names aren't consistent enaough t filter with a regexp.

Could you implement this type of filtering?

Thanks.

**Comment by mvisonneau** [comment]
That sounds interesting, do you mean `topics` ? I am not sure how to get a list of project based on topics from the GitLab API though? 🤔

**Comment by mvisonneau** [comment]
Waiting on https://gitlab.com/gitlab-org/gitlab/issues/14530

**Comment by mvisonneau** [comment]
I added a new label to the metrics : `topics` https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/81540c7a4a3e6994ca68c33c8fe4dfd5d2d1c900

it will allow you to filter on the prometheus side instead of the collector side.

**Comment by mvisonneau** [comment]
I released it in `0.2.10` ☝️

**Comment by Cobra1978** [comment]
Thanks!!!!
