### ISSUE TITLE
gitlab_ci_pipeline_run_count is incremented multiple times

### ISSUE THREAD

**Issue by Clement87** [mvisonneau/gitlab-ci-pipelines-exporter#355]
Hi,  
`gitlab_ci_pipeline_run_count` is returning wrong value because the increment is run multiple times per pipeline.

The issue seems to be [here](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/174a477d0f9a52f340ed606d0e96c88efa4f4e29/pkg/controller/pipelines.go#L81).  
I believe the code should be:

```go
		if formerPipeline.ID != 0 && formerPipeline.ID != ref.LatestPipeline.ID {
			runCount.Value++
		}
```

Otherwise, runCount is incremented everytime `!reflect.DeepEqual(pipeline, ref.LatestPipeline)` is true ([L56](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/174a477d0f9a52f340ed606d0e96c88efa4f4e29/pkg/controller/pipelines.go#L56)).  
As a reminder, values of `pipeline` and `ref.LatestPipeline` can be:
```
pipeline="{3986797 0 1.635240859e+09 13 48.187 success }" ref.LatestPipeline="{3986797 0 1.635240859e+09 13 48.187 success }"
pipeline="{3990193 0 1.635242406e+09 0 1.71 running }" ref.LatestPipeline="{3986797 0 1.635240859e+09 13 48.187 success }"
pipeline="{3990193 0 1.635242421e+09 15 1.71 success }" ref.LatestPipeline="{3990193 0 1.635242406e+09 0 1.71 running }"
```

I can submit a Pull Request if needed.
Best,
Clement

**Comment by DimitriHumblot** [comment]
+1

**Comment by seohs7** [comment]
+1

> +1

**Comment by Clement87** [comment]
Thanks @mvisonneau for the acknowledgment, can I add some more help like a Pull Request with the fix shown below ?

**Comment by mvisonneau** [comment]
👋 hey @Clement87, my bad I was planning to look into it but got carried away over the past few months 🙇 If you want to have a shot at it of course, happy to review it!

**Comment by Clement87** [comment]
Thanks @mvisonneau, the PR is here https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/384
Best, Clement
