### ISSUE TITLE
Secure/restrict metrics endpoint

### ISSUE THREAD

**Issue by jkroepke** [mvisonneau/gitlab-ci-pipelines-exporter#365]
Hi, 

I would like to know, if it's possible to configure something like a secret token (which needs to be passed as GET parameter or http header) to secure the /metrics endpoint.

**Comment by mvisonneau** [comment]
👋 hey @jkroepke,

It is unfortunately not currently possible to do so. Are you using it over HTTPS? If no, I am not sure how this would add security value. If yes, isn't it possible to achieve this at your network/reverse proxy layer? 🤔

**Comment by mvisonneau** [comment]
Will now close this issue as I believe it is currently out of scope for this project. I assume there are various ways to secure it leveraging more appropriated solutions.
