### ISSUE TITLE
pipeline coverage is no longer a string in the api

### ISSUE THREAD

**Issue by vgropp** [mvisonneau/gitlab-ci-pipelines-exporter#376]
Hi,

very recently, gitlab.com changed the API for the SaaS version with https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75329. We are not able to retrieve our pipeline metrics because of this change any more (`could not read content of pipeline <project> - <ref> | json: cannot unmarshal number into Go struct field Pipeline.coverage of type string`). go-gitlab has already a MR open: https://github.com/xanzy/go-gitlab/pull/1307, but in my consideration this is a breaking change as this probably won't work for older on premise versions. 

Any idea to handle this issue without waiting for the new version of go-gitlab and to depend on the upcoming gitlab 14.6?

**Comment by Ravlen** [comment]
@vgropp Hey, turns out this was not intentional, it was a bug, and it should hopefully be resolved with https://gitlab.com/gitlab-org/gitlab/-/merge_requests/76299

**Comment by vgropp** [comment]
@Ravlen  glad to hear this. My gitlab support told me, that it was an intentionally change. As i pointed the missing documentation change out,  he even asked me to do a MR for the docs next time myself.

**Comment by vgropp** [comment]
issue in gitlab.com is resolved
