### ISSUE TITLE
Grafana dashboards

### ISSUE THREAD

**Issue by ArjonBu** [mvisonneau/gitlab-ci-pipelines-exporter#4]
Would you be able to share the grafana dashboards that you build? They seem to be practical. 

Thanks

**Comment by phlaxyz** [comment]
i would love to see a quick tutorial how to implement it as a datasource in grafana as well, i installed it with helm and im kind of stuck

**Comment by mvisonneau** [comment]
I just published the dashboard I am now using on Grafana.com : https://grafana.com/grafana/dashboards/10620

I will update the doc and craft a more end-to-end getting started guide 👍

**Comment by ArjonBu** [comment]
Thanks!
