### ISSUE TITLE
arm support?

### ISSUE THREAD

**Issue by bjornarhagen** [mvisonneau/gitlab-ci-pipelines-exporter#405]
Hey I'm trying to run the "quickstart" example I'm getting this:

```
docker-compose up -d

Creating network "quickstart_default" with driver "bridge"
Pulling gitlab-ci-pipelines-exporter (docker.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.5.2)...
v0.5.2: Pulling from mvisonneau/gitlab-ci-pipelines-exporter
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Is arm not support? Would it be possible to add it?

**Comment by mvisonneau** [comment]
👋 hey @bjornarhagen, thanks for raising this issue! I have added the support with the following commit: 59be7df

I hope this will sort your issue!

**Comment by bjornarhagen** [comment]
It works perfectly now! Thanks a lot for the quick response 😄
