### ISSUE TITLE
Ability to set concurrency for scanning

### ISSUE THREAD

**Issue by Dentrax** [mvisonneau/gitlab-ci-pipelines-exporter#406]
I'm not sure whether we currently support concurrency to scan entire GitLab but it would be nice to set `concurrency: int` in [configuration](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/aac011d2cb0637c68237338a9e832c8784093d42/pkg/config/config.go#L87). What do you think?

**Comment by JohnWillker** [comment]
In my tests to discover more than 3k repositories takes ~15 minutes, a concurrency would be nice.

**Comment by mvisonneau** [comment]
Concurrency is indeed implemented, you can see the default values relating to the processing of the tasks over here: https://github.com/mvisonneau/taskq/blob/v3/queue.go#L16-L27

I am not convinced it would make sense to provide custom configuration capabilities though as the limiting factor will likely always be the GitLab's API RPS which you can set here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/aac011d2cb0637c68237338a9e832c8784093d42/pkg/config/config.go#L104

**Comment by jwillker** [comment]
> Concurrency is indeed implemented, you can see the default values relating to the processing of the tasks over here: https://github.com/mvisonneau/taskq/blob/v3/queue.go#L16-L27
> 
> I am not convinced it would make sense to provide custom configuration capabilities though as the limiting factor will likely always be the GitLab's API RPS which you can set here:
> 
> https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/aac011d2cb0637c68237338a9e832c8784093d42/pkg/config/config.go#L104

That makes sense, thanks
