### ISSUE TITLE
0.5.3 quickstart  msg="could not find any pipeline for the ref"

### ISSUE THREAD

**Issue by mayuming813** [mvisonneau/gitlab-ci-pipelines-exporter#407]
time="2022-02-16T12:13:50Z" level=debug msg="could not find any pipeline for the ref" project-name=gaotu/course-setting ref=v1.4.70 ref-kind=tag
  level: debug

gitlab:
  url: *********
  token: **********

project_defaults:
  pull:
    refs:
      merge_requests:
        enabled: true

projects:
  - name: gaotu/course-setting

**Comment by mvisonneau** [comment]
feel free to reopen with further explanations
