### ISSUE TITLE
gitlab_ci_pipeline_job_queued_duration_seconds is producing wrong results for manual jobs

### ISSUE THREAD

**Issue by Rurouni** [mvisonneau/gitlab-ci-pipelines-exporter#437]
Hi,

I've noticed some jobs with very long queue time on dashboard and after investigation, it appeared that it happens because job queue time is calculated as `queued = gj.StartedAt.Sub(*gj.CreatedAt)`  but for manual jobs that will lead to including time that job was waiting to be manually started.  Gitlab returns `queued_duration` property in that job REST call results and I think it will be better to use it

Thank you

**Comment by mvisonneau** [comment]
👋 hey @Rurouni, thanks for the heads up, it should be fixed through 92acee3 !

**Comment by Rurouni** [comment]
Huge thanks for the fast fix @mvisonneau!  Are you planning to release a new docker image with that fix any time soon?
