### ISSUE TITLE
many projects, gitlab goes down after running ci pipeline exporter for a couple of hours

### ISSUE THREAD

**Issue by virtuman** [mvisonneau/gitlab-ci-pipelines-exporter#44]
I see that defaults for pulling pipelines and discovering projects are pretty safe, yes our gitlab instance cannot handle the load. Is there currently some throttling mechanism that allows to prevent API query overflow , like no more that N number of simultaneous requests?

Thank you

**Comment by mvisonneau** [comment]
👋 hey @virtuman, thanks for raising this issue. I had in mind to implement such a feature for a while. I've just done it in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/5e80cb835b64de0a1d4352c2de54ac75e7f51d72 it will be part of the next release!

**Comment by mvisonneau** [comment]
it is part of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.2.11
