### ISSUE TITLE
error="listen: unknown network "

### ISSUE THREAD

**Issue by mims92** [mvisonneau/gitlab-ci-pipelines-exporter#454]
With the latest docker image https://hub.docker.com/layers/gitlab-ci-pipelines-exporter/mvisonneau/gitlab-ci-pipelines-exporter/latest/images/sha256-ad0849167c27b54ff2277786fe6d54b768d61fdd0bb0c3cb5563437823a14b16?context=explore, the problem occurs when launching the docker container.

Log:
`gitlab-ci-exporter_1  | time="2022-05-10T09:18:38Z" level=fatal error="listen: unknown network "`

It does not happen on v0.5.3

**Comment by KnKay** [comment]
Same here, with building from source! 
Anything that need to be additional set maybe?

**Comment by ancordier** [comment]
Same here while updating the latest docker image few days ago.

**Comment by oijkn** [comment]
Same here with last docker image.
