### ISSUE TITLE
groups and projects name from metrics...

### ISSUE THREAD

**Issue by manasmehrotra28** [mvisonneau/gitlab-ci-pipelines-exporter#55]
through this exporter we get metrics like ex: 
gitlab_runner_counts(project="<groups_name>/<project_name>"
is there is any way to get group name and project name separately like this:
gitlab_runner_counts(group="<group_name>",project="<project_name>")

any solution for this??

**Comment by mvisonneau** [comment]
I believe you can use a a remap rule to achieve this purpose 🤔

**Comment by PG2000** [comment]
> I believe you can use a a remap rule to achieve this purpose 🤔

Can you explain this a little bit?
