### ISSUE TITLE
Gitlab Job IDs in Grafana always refer to Gitlab.com

### ISSUE THREAD

**Issue by LGhoull** [mvisonneau/gitlab-ci-pipelines-exporter#573]
It would be optimal to have them refer to the gitlab URL specified in the config. If I want to change the link on my own, how do I do that?

**Comment by albang** [comment]
You have to change the env variable of the grafana dashboard 
![image](https://user-images.githubusercontent.com/3199329/222692921-d508c6d7-34ca-4d5a-8e39-2390376ecaec.png)
edit the variable :
![image](https://user-images.githubusercontent.com/3199329/222693119-ac03d229-6f9b-44d0-b079-bcf78fcd8661.png)
go back to the dashboard. save as json, 
![image](https://user-images.githubusercontent.com/3199329/222693559-735886a3-7dc3-4b74-b7f0-18c5ffde0481.png)
and reimport the template with different name and id.
![image](https://user-images.githubusercontent.com/3199329/222694337-28c2f146-babd-40b4-84dc-125907db86de.png)
![image](https://user-images.githubusercontent.com/3199329/222694489-0e24c23d-70a6-47bf-8b5a-23281c38ba27.png)
