### ISSUE TITLE
Buffer size exhausted

### ISSUE THREAD

**Issue by DurgeshBarve** [mvisonneau/gitlab-ci-pipelines-exporter#580]
Trying to fetch more than 1000 branches . But getting buffer size exhausted error after 1000 . how can I increase the buffer size?

**Comment by mikaello** [comment]
Duplicate of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/327, @mvisonneau has some suggestions here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/327#issuecomment-1171415537

**Comment by DurgeshBarve** [comment]
Tried all the approach suggested in comment 327 but still getting warning

**Comment by mvisonneau** [comment]
in case you really need it, I've added a [new configuration parameter](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/90444f156508db4457a4025dcd7851a63ec5aaa8#diff-4194838c0fad9762c5a0e565dd61998e713f6710b58d5d8bd6bf19005ab589caR97-R106) (available from [v0.5.5](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.5.5))
