### ISSUE TITLE
Count of Pipeline executions

### ISSUE THREAD

**Issue by cavit2807** [mvisonneau/gitlab-ci-pipelines-exporter#60]
Hello,

is it possible to get the pipeline executions within a specific time period and to add this kind of informations in a panel in the grafana dashboard?

**Comment by mvisonneau** [comment]
Indeed, you can use the `gitlab_ci_pipeline_run_count` metric for this purpose.

On the other end, the Grafana dashboard I provide in this repository is for example only, I do not intend to maintain it and make it fit everyone's requirements unfortunately.
