### ISSUE TITLE
Issue with storage

### ISSUE THREAD

**Issue by ubershloder** [mvisonneau/gitlab-ci-pipelines-exporter#626]
Where does this exporter store all the data it fetched?
for some reason every time I restart the container with it all the fetched data is gone. 
is there any way to prevent it? like maybe store it in some place somehow?

**Comment by hanyce** [comment]
have the same problem. anyone can help?

**Comment by adeqecil** [comment]
I'm also wondering. If the exporter restart, I think they scraping all over from start again although the metrics has been scraped and stored in prometheus before.

I think the exporter should know whether the projects, groups, etc has been scraped before and no need to scrape again if the exporter got restarted.

**Comment by f0rkth1s** [comment]
I have the same issue, I even setup efs storage for the /prometheus mount point, I can see the data growing. But every time the container restarts, all data is scraped again
