### ISSUE TITLE
[Feature] Refreshing projects

### ISSUE THREAD

**Issue by DJMatus23** [mvisonneau/gitlab-ci-pipelines-exporter#65]
We've come up with another little feature enhancement.  Currently the only time the exporter gets a list of projects is on startup.  We've had an instance running for a few weeks, but as we're regularly creating new repos, they're not getting picked up.

The 2 options I can think of are:

1. After a certain amount of time, drop back from polling to getting the project list again.
1. After a certain amount of time, exit the app and let either systemd or the container schedule restart from scratch.

What do you reckon?

**Comment by paulbygrave** [comment]
Does it pick up new projects if you use a wildcard entry?
eg.
wildcards:
  - refs: ".*"

Looking at the config file it does suggest the exporter is supposed to poll for a list of projects if you use wildcards:

# Custom waiting time between polls for projects, their refs and pipelines (in seconds, optional)
projects_polling_interval_seconds: 1800 # only used for wildcards

**Comment by DJMatus23** [comment]
You're absolutely right, I totally missed that, thanks for point that out.

**Comment by mvisonneau** [comment]
I confirm, it should automatically poll new projects for wildcards. Feel free to reopen if not!
