### ISSUE TITLE
Container scanning on later versions fails due to busybox base image

### ISSUE THREAD

**Issue by paulbygrave** [mvisonneau/gitlab-ci-pipelines-exporter#68]
Love the project and is just what I need for my current task, but all containers in our environment need to be clair scanned before they can be used.
Thing is, since the move to using busybox base images in 0.23 the containers can't be scanned, as Clair doesn't recognise busybox as a valid base OS.
Are there any post-0.22 changes that would break if I used alpine as a base image? I couldn't find any reasoning behind the base image change in the release notes.

**Comment by mvisonneau** [comment]
it should be working perfectly fine on alpine too 👍

**Comment by paulbygrave** [comment]
> it should be working perfectly fine on alpine too 👍

Thanks Maxime, I can confirm that it builds, runs and scans fine with an alpine base! Much appreciated.
