### ISSUE TITLE
Select to include (or not) tags in discovery

### ISSUE THREAD

**Issue by vakaobr** [mvisonneau/gitlab-ci-pipelines-exporter#72]
Hello there, long time without coming here! :)

Its possible to add a flag, to fetch (or not) tags from the discovered projects?

In my example here, we're using tags only for create releases, but not creating branches for each one of those, and when discover happens, all tags shows as branches on "healthy" dashboard section:

![Screenshot 2020-03-10 at 08 52 00](https://user-images.githubusercontent.com/15154330/76295588-c9eef880-62ac-11ea-9572-47c55b24c138.png)

**Comment by mvisonneau** [comment]
👋 hey @vakaobr! I am unfortunately not sure to understand your question.

I believe you can already filter in/out the tags you want as `ref` can be used for either a `branch` or a `tag`.

**Comment by vakaobr** [comment]
ohhh, probably I've let this pass, I'll try it tomorrow. Thanks!

**Comment by mvisonneau** [comment]
I will close it for now, feel free to reopen if there is anything wrong with what I suggested!
