### ISSUE TITLE
Get metrics for jobs for pipeline

### ISSUE THREAD

**Issue by espenkm** [mvisonneau/gitlab-ci-pipelines-exporter#73]
It would be very nice to be able to break the piplines down to the job level to be able to see how long each job takes, what job is currently running for a pipeline and what part of a pipeline did actually fail.

I'm not much of a go programmer, but could give it a go if it is something you think is a good idea

**Comment by mvisonneau** [comment]
thanks for raising this issue @espenkm. Indeed, I believe this is an excellent idea. Given the current specs of the GitLab API I reckon this should be possible https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-jobs

**Comment by DJMatus23** [comment]
The way we've dealt with this is to add tracing steps to all of our jobs.  So add a before_script which puts a timestamp into a file in /tmp, then in the after_script read that value out and send it through to your tracing solution.  That way you can gather a lot more data on each job (like env vars, etc.), and do deeper analysis on any slow jobs.

**Comment by mvisonneau** [comment]
I am going to close this one as it has this feature has now been merged (#77) and released in `0.2.13`
