### ISSUE TITLE
Readiness probe always return HTTP 503

### ISSUE THREAD

**Issue by gaeljw** [mvisonneau/gitlab-ci-pipelines-exporter#777]
We've noticed that the Readiness probe always returns HTTP 503 even though the service seems to work perfectly fine.

Here's a cURL output (using a port forward):
```
curl -v 'http://localhost:42523/health/ready'
* processing: http://localhost:42523/health/ready
*   Trying [::1]:42523...
* Connected to localhost (::1) port 42523
> GET /health/ready HTTP/1.1
> Host: localhost:42523
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Content-Type: application/json; charset=utf-8
< Date: Tue, 16 Jan 2024 15:28:31 GMT
< Content-Length: 3
< 
{}
```

We're using the Helm chart v0.3.1 (version 0.5.5 of the app).

There's no relevant information in the logs that would explain the error.

Any idea why this happens?

**Comment by gaeljw** [comment]
Oops, it's a duplicate of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/393

Adding a trailing slash to the `config.gitlab.url` fixed it :)

**Comment by digitalstudium** [comment]
@gaeljw It works, thank you! i wonder how could it was even possible to realize how to solve it by trailing slash )
