### ISSUE TITLE
I got failed when update chart to version 0.2.13.

### ISSUE THREAD

**Issue by Eji4h** [mvisonneau/gitlab-ci-pipelines-exporter#78]
Failed to install app gitlab-ci-pipelines-exporter. Error: YAML parse error on gitlab-ci-pipelines-exporter/templates/service.yaml: error converting YAML to JSON: yaml: line 11: could not find expected ':'

I saw change from [Add service labels in helm template](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/f17969f9b38c493c7c0792942a6fc858b6b1199c#diff-e3d1935e3c9ce29c41c3fa660f9f72a9).

**Comment by mvisonneau** [comment]
Thanks for raising this @Eji4h!

it should be fixed in 4a9101b
