### ISSUE TITLE
Wildcard for refs

### ISSUE THREAD

**Issue by heironeous** [mvisonneau/gitlab-ci-pipelines-exporter#8]
Hello Mvisonneau,

I would like to be able to fetch all refs within a project. We have only a handful of projects, but we have many branches / merge requests. We'd like to import all of these into prometheus, and do the filtering in grafana or in prometheus. Is this possible?

If not, I can also try and create a PR for this as well, if you'd point to me where I should start from

**Comment by mvisonneau** [comment]
👋 hey @heironeous, yes I believe it should be possible to fetch all the refs or base it on a wildcard. I'll have a look onto it.

**Comment by mvisonneau** [comment]
This should now be supported with https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/5f6fa05320672a4b60a587b7083f6d56662decd2 🎉

**Comment by heironeous** [comment]
That was very fast! Thank you very much, I'll see about this
