### ISSUE TITLE
Label job is reserved by Prometheus

### ISSUE THREAD

**Issue by MMore** [mvisonneau/gitlab-ci-pipelines-exporter#83]
Hey,

first of all: thank you for this awesome exporter. It's really useful and well done :) 

I just noticed that the exporter uses a label `job` which is actually "reserved" by [Prometheus](https://prometheus.io/docs/concepts/jobs_instances/). It looks like other exporters like the [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md#v140-rc0--2018-08-06) renamed their label `job` as well to mitigate the problem.

Therefore I propose to rename the label `job` to `job_name`. What do you think about it?

**Comment by mvisonneau** [comment]
oh indeed, this must be following https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/77! I will have a look and push a fix asap.
