### ISSUE TITLE
Wildcard projects but master branches only

### ISSUE THREAD

**Issue by paulbygrave** [mvisonneau/gitlab-ci-pipelines-exporter#84]
Hey,

Been playing around with the exporter a bit and believes there's an error or inconsistency in the config.yaml file:

```
# Default regexp for parsing the refs (branches and tags) to monitor (optional, default to master)
# default_refs: "^master$"

# Search for projects globally
  - refs: ".*"
    search: 'baz' # optional (defaults to '')
    archived: true # optional (default: false)
```

Asssuming I want to monitor all projects but only the master branches, this config should work, as the first section defaults to master branches and the projects wildcard is set to find all projects, but instead it's exporting all branches of all projects.

Is there a configuration combination that does what I'm looking for?

**Comment by mvisonneau** [comment]
If you override the `default_refs: "^master$"` with `refs: ".*"` in your wildcard, you are instructing it to fetch all branches.

A presumably working configuration for the scenario you described would be:

```yaml
wildcards:
  - {}
```

or if you want to fetch archived projects too:

```yaml
wildcards:
  - archived: true
```

**Comment by paulbygrave** [comment]
Worked like a charm Maxime, thanks!
