### ISSUE TITLE
Polling with goroutines

### ISSUE THREAD

**Issue by inge4pres** [mvisonneau/gitlab-ci-pipelines-exporter#86]
Thanks for this project @mvisonneau!
We use GitLab and this project has a great value to monitor how we are performing.
This is more of a general design discussion rather than a real issue with the product.

While trying to refactor some part of the code to add a feature I noticed that the when the method `Client.pollProject` is called at gitlab.go#128](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/cmd/gitlab.go#L128) and [gitlab.go#426](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/cmd/gitlab.go#L426) is never signalled for completion, so the goroutine will never return neither report the errors (only logging them), it will just loop for all projects with a `time.Sleep` at the end of it.
While this approach can work fine for a limited amount or projects, it does not scale well when the project number start to grow, especially with regards to the shared API client with rate limiting applied.

Another approach would be to build a processing pipeline that fans out to a limited number of processing goroutines doing the heavy-lifting of querying the GitLab API and fanning into the prometheus metrics collection.
I'll try to create a PR showing this in the next days so we can discuss.

**Comment by inge4pres** [comment]
Thanks for merging the PR! We can close this issue once a new release is published

**Comment by mvisonneau** [comment]
This is now part of [0.3.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.3.0)

Thanks again for your help on this @inge4pres ! 🙇
