### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by mvisonneau** [mvisonneau/gitlab-ci-pipelines-exporter#90]
@inge4pres, I was running some tests with a master build locally and ran into the following error:

```
panic: send on closed channel

goroutine 41 [running]:
github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProjectsWith.func1(0xc000192480, 0xc0000f61e0, 0xc00012fd00, 0xc000192780)
	/go/gitlab-ci-pipelines-exporter/cmd/gitlab.go:483 +0x1b2
created by github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProjectsWith
	/go/gitlab-ci-pipelines-exporter/cmd/gitlab.go:476 +0x120
```

I'll try to dig into it later on, just to let you know! :)

nb: probably related to https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/88

**Comment by inge4pres** [comment]
yes, looks like a problem on writing back the error generated by a worker...
I think i need a more thorough testing of that part and I have a fix in mind, I'll send it over soon

**Comment by inge4pres** [comment]
Oops 😄 looks like i did not test properly but hopefully there is coverage now.
I added `-race` tests flag and a dedicated test for this method so we can catch errors like these further on.
Sorry for the inconvenience...

**Comment by mvisonneau** [comment]
no worries, thanks a lot for the quick PR!
