### ISSUE TITLE
Merge Request Pipelines

### ISSUE THREAD

**Issue by jdelah** [mvisonneau/gitlab-ci-pipelines-exporter#95]
Hello ! 
First of all, thank very much for your job ! I was able to get a CI status Dashboard for all the devs in my company.
All is working pretty smooth and correctly, but i still have an issue.

I can't retrieve Pipeline Status from merge request. I used wildcard to retrieve all groups / refs possible but merges requests pipelines won't come up.

From the image below, i'm able to get the release/1.1 pipeline status but not the "60" as it's a merge request.
![image](https://user-images.githubusercontent.com/23212553/80463485-9b021400-8938-11ea-805e-73ead46c51a7.png)

Any ideas ? Did i miss something ?

Regards,

**Comment by mvisonneau** [comment]
Hi @jdelah, thanks for the kind feedbacks 🙇 

Indeed, these refs do not get exposed through the GitLab API endpoint for the project. The only way to get them now would be to set `on_init_fetch_refs_from_pipelines: true` and have a `refs_regexp` which can catch them like : `^refs/merge-requests/.*`

Unfortunately, this will only work for the `n` most recent ones and will not be fetching any new ones once the exporter is started.

I believe it could be possible to implement a feature that look for them though.

**Comment by mvisonneau** [comment]
This should now be supported following f52cb27fca61fbcd133e19f5f457f07d2ed435ea :)

**Comment by mvisonneau** [comment]
this is part of [0.3.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.3.0)

feel free to reopen if it does not address your issue!

**Comment by jdelah** [comment]
First of all thank you for considering my enhancement !

I upgraded to the 0.3.0 version, but can't get anymore data.
I'm using your docker images, logs telling me

`level=info msg="discovered new project ref" project-id=660 project-path-with-namespace=customer/android project-ref=release/1.1 project-ref-kind=branch`

But it stops on 

`"level=info msg="polling metrics from projects refs" count=5"`

At this time, docker still running, but not a single metrics is retrieved.
Already changed many of your config and rolled back to the original in your example, no changes.

Any ideas ?

Thanks for you time !

**Comment by mvisonneau** [comment]
👋 hey @jdelah, indeed a bug was introduced in 0.3.0, sorry about that. This relates to #97, you can try to upgrade to 0.3.1, it should sort this issue out 🤞
