### ISSUE TITLE
Add pipeline id as label

### ISSUE THREAD

**Issue by thiagoalmeidasa** [mvisonneau/gitlab-ci-pipelines-exporter#99]
Great work on this tool, just started to use and it is dope! I hope GitLab integrates it as the official pipeline exporter in the future.

Would be possible to add pipeline id as a label? Then I could make some links to failed pipelines from the dashboard.

**Comment by mvisonneau** [comment]
👋 hey @thiagoalmeidasa , thanks for the kind feedback 🙇 

You should have the `gitlab_ci_pipeline_last_run_id` to get you the ID of the most recent pipeline. Is is what you were looking for?

**Comment by mvisonneau** [comment]
I am going to close this as I feel that this would not seem to be sustainable/reasonable in terms of label # if we add 1 per pipeline.
